workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    mintlify:
        inputs:
            - location: https://spec.speakeasy.com/polar/polar/polar-oas-with-code-samples
            - fallbackCodeSamplesLanguage: typescript
        output: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/polar/polar/mintlify
targets: {}
