# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "uv"
    directory: "/server"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/server/emails"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      react-email:
        patterns:
          - "react-email"
          - "@react-email/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    directory: "/handbook"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
