#!/bin/bash

set -e

host="localhost"
user="polar"
password="polar"
test_database="polar"

# Create role if it doesn't exist
if ! PGPASSWORD=$password psql -h "$host" -U "postgres" -tAc "SELECT 1 FROM pg_roles WHERE rolname='$user'" | grep -q 1; then
  PGPASSWORD=$password psql -h "$host" -U "postgres" -c "CREATE ROLE $user WITH LOGIN PASSWORD '$password';"
else
  echo "Role $user already exists."
fi

# Grant CREATEDB privilege to the role
PGPASSWORD=$password psql -h "$host" -U "postgres" -c "ALTER ROLE $user CREATEDB;"

# Create database if it doesn't exist
if ! PGPASSWORD=$password psql -h "$host" -U "$user" -d "postgres" -tAc "SELECT 1 FROM pg_database WHERE datname='$test_database'" | grep -q 1; then
  PGPASSWORD=$password psql -h "$host" -U "$user" -d "postgres" -c "CREATE DATABASE $test_database;"
else
  echo "Database $test_database already exists."
fi
