# ============================================================================
# DigitalOcean App Platform Configuration for AgentPay
# ============================================================================
# Deploy to: https://cloud.digitalocean.com/apps
# Documentation: https://docs.digitalocean.com/products/app-platform/
# ============================================================================

name: agentpay
region: nyc  # Options: nyc (New York), sfo (San Francisco), ams (Amsterdam), sgp (Singapore)

# ============================================================================
# Services
# ============================================================================
services:
  # API Server
  - name: api
    github:
      repo: muriloscigliano/flowpay
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: |
      cd server && \
      pip install uv && \
      uv sync && \
      uv run task emails
    run_command: |
      cd server && \
      uv run alembic upgrade head && \
      uv run uvicorn polar.app:app --host 0.0.0.0 --port 8080 --workers 4

    http_port: 8080

    instance_count: 1
    instance_size_slug: professional-xs  # $12/month (512MB RAM, 1 vCPU)

    health_check:
      http_path: /healthz
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    routes:
      - path: /

    envs:
      # Application
      - key: POLAR_ENV
        value: "production"

      - key: POLAR_BASE_URL
        value: "${APP_URL}"

      - key: POLAR_SECRET
        type: SECRET
        value: "${POLAR_SECRET}"

      - key: POLAR_CORS_ORIGINS
        value: "https://yourdomain.com"

      # Database (auto-linked)
      - key: POLAR_POSTGRES_DSN
        value: "${agentpay-db.DATABASE_URL}"
        type: SECRET

      # Redis (auto-linked)
      - key: POLAR_REDIS_URL
        value: "${agentpay-redis.REDIS_URL}"
        type: SECRET

      # LLM - Anthropic
      - key: ANTHROPIC_API_KEY
        type: SECRET
        value: "${ANTHROPIC_API_KEY}"

      - key: ANTHROPIC_MODEL
        value: "claude-3-5-sonnet-20241022"

      - key: ANTHROPIC_INTENT_MODEL
        value: "claude-3-haiku-20240307"

      - key: ANTHROPIC_ENABLE_CACHING
        value: "true"

      # LLM - OpenAI
      - key: OPENAI_API_KEY
        type: SECRET
        value: "${OPENAI_API_KEY}"

      - key: OPENAI_EMBEDDING_MODEL
        value: "text-embedding-3-small"

      # Stripe
      - key: POLAR_STRIPE_SECRET_KEY
        type: SECRET
        value: "${POLAR_STRIPE_SECRET_KEY}"

      - key: POLAR_STRIPE_PUBLISHABLE_KEY
        value: "${POLAR_STRIPE_PUBLISHABLE_KEY}"

      - key: POLAR_STRIPE_WEBHOOK_SECRET
        type: SECRET
        value: "${POLAR_STRIPE_WEBHOOK_SECRET}"

      - key: POLAR_STRIPE_CONNECT_WEBHOOK_SECRET
        type: SECRET
        value: "${POLAR_STRIPE_CONNECT_WEBHOOK_SECRET}"

      # S3 Storage (DigitalOcean Spaces)
      - key: S3_ENDPOINT_URL
        value: "https://nyc3.digitaloceanspaces.com"

      - key: S3_ACCESS_KEY_ID
        type: SECRET
        value: "${SPACES_ACCESS_KEY}"

      - key: S3_SECRET_ACCESS_KEY
        type: SECRET
        value: "${SPACES_SECRET_KEY}"

      - key: S3_BUCKET_NAME
        value: "agentpay-production"

      - key: S3_REGION
        value: "nyc3"

      # Monitoring
      - key: SENTRY_DSN
        type: SECRET
        value: "${SENTRY_DSN}"

      - key: LOG_LEVEL
        value: "INFO"

      # AgentPay Settings
      - key: AGENTPAY_ENABLE_STREAMING
        value: "true"

      - key: AGENTPAY_ENABLE_TYPING_INDICATOR
        value: "true"

      - key: AGENTPAY_MAX_HISTORY_LENGTH
        value: "20"

      - key: AGENTPAY_RAG_SIMILARITY_THRESHOLD
        value: "0.75"

      - key: AGENTPAY_RAG_MAX_RESULTS
        value: "5"

      # Performance
      - key: WORKER_THREADS
        value: "4"

      - key: DB_QUERY_TIMEOUT
        value: "30"

      - key: LLM_REQUEST_TIMEOUT
        value: "60"

  # Background Worker
  - name: worker
    github:
      repo: muriloscigliano/flowpay
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: |
      cd server && \
      pip install uv && \
      uv sync
    run_command: |
      cd server && \
      uv run task worker

    instance_count: 1
    instance_size_slug: professional-xs  # $12/month

    envs:
      # Inherit database and redis from API
      - key: POLAR_POSTGRES_DSN
        value: "${agentpay-db.DATABASE_URL}"
        type: SECRET

      - key: POLAR_REDIS_URL
        value: "${agentpay-redis.REDIS_URL}"
        type: SECRET

      # LLM keys
      - key: ANTHROPIC_API_KEY
        type: SECRET
        value: "${ANTHROPIC_API_KEY}"

      - key: OPENAI_API_KEY
        type: SECRET
        value: "${OPENAI_API_KEY}"

      # S3
      - key: S3_ACCESS_KEY_ID
        type: SECRET
        value: "${SPACES_ACCESS_KEY}"

      - key: S3_SECRET_ACCESS_KEY
        type: SECRET
        value: "${SPACES_SECRET_KEY}"

      # Worker settings
      - key: WORKER_THREADS
        value: "4"

      - key: WORKER_CONCURRENCY
        value: "10"

      - key: LOG_LEVEL
        value: "INFO"

# ============================================================================
# Databases
# ============================================================================
databases:
  # PostgreSQL with pgvector
  - name: agentpay-db
    engine: PG
    version: "15"
    size: db-s-1vcpu-1gb  # $15/month (1GB RAM, 1 vCPU, 10GB storage)
    num_nodes: 1
    production: true

    # Note: Enable pgvector after creation:
    # 1. Go to database console
    # 2. Run: CREATE EXTENSION IF NOT EXISTS vector;

  # Redis
  - name: agentpay-redis
    engine: REDIS
    version: "7"
    size: db-s-1vcpu-1gb  # $15/month (1GB RAM)
    num_nodes: 1
    production: true

# ============================================================================
# Static Sites (Optional - for widget CDN)
# ============================================================================
static_sites:
  - name: widget-cdn
    github:
      repo: muriloscigliano/flowpay
      branch: main
      deploy_on_push: true
    source_dir: /clients/packages/agentpay-chat/dist
    build_command: |
      cd clients/packages/agentpay-chat && \
      npm install && \
      npm run build
    output_dir: /clients/packages/agentpay-chat/dist
    routes:
      - path: /widget

# ============================================================================
# Deployment Instructions
# ============================================================================
#
# 1. Install doctl (DigitalOcean CLI):
#    brew install doctl
#    doctl auth init
#
# 2. Create app:
#    doctl apps create --spec .do/app.yaml
#
# 3. Set secrets in DigitalOcean dashboard:
#    - POLAR_SECRET (generate: openssl rand -hex 32)
#    - ANTHROPIC_API_KEY
#    - OPENAI_API_KEY
#    - POLAR_STRIPE_SECRET_KEY
#    - POLAR_STRIPE_WEBHOOK_SECRET
#    - POLAR_STRIPE_CONNECT_WEBHOOK_SECRET
#    - SPACES_ACCESS_KEY (DigitalOcean Spaces)
#    - SPACES_SECRET_KEY
#    - SENTRY_DSN (optional)
#
# 4. Enable pgvector extension:
#    - Go to database console
#    - Run: CREATE EXTENSION IF NOT EXISTS vector;
#    - Verify: \dx
#
# 5. Deploy:
#    doctl apps update <APP_ID> --spec .do/app.yaml
#
# 6. Monitor:
#    doctl apps logs <APP_ID>
#
# ============================================================================
# Cost Breakdown (DigitalOcean)
# ============================================================================
#
# API Server:           $12/month (professional-xs)
# Worker:               $12/month (professional-xs)
# PostgreSQL:           $15/month (db-s-1vcpu-1gb)
# Redis:                $15/month (db-s-1vcpu-1gb)
# ---------------------------------------------------
# Total:                $54/month 💰 (Most affordable!)
#
# Upgrade paths:
# - API/Worker → professional-s ($24/mo each) for more traffic
# - Database → db-s-2vcpu-4gb ($60/mo) for more storage
# - Add CDN ($5/mo) for global distribution
#
# ============================================================================
