export const tokens = {
  "COLOR_BG": "var(--COLOR_BG)",
  "COLOR_BG_SURFACE": "var(--COLOR_BG_SURFACE)",
  "COLOR_BG_ELEVATED": "var(--COLOR_BG_ELEVATED)",
  "COLOR_TEXT": "var(--COLOR_TEXT)",
  "COLOR_TEXT_SUBTLE": "var(--COLOR_TEXT_SUBTLE)",
  "COLOR_TEXT_DISABLED": "var(--COLOR_TEXT_DISABLED)",
  "COLOR_DESTRUCTIVE": "var(--COLOR_DESTRUCTIVE)",
  "COLOR_BUTTON_PRIMARY_BG": "var(--COLOR_BUTTON_PRIMARY_BG)",
  "COLOR_BUTTON_PRIMARY_FG": "var(--COLOR_BUTTON_PRIMARY_FG)",
  "COLOR_BUTTON_SECONDARY_BG": "var(--COLOR_BUTTON_SECONDARY_BG)",
  "COLOR_BUTTON_SECONDARY_FG": "var(--COLOR_BUTTON_SECONDARY_FG)",
  "COLOR_BUTTON_DESTRUCTIVE_FG": "var(--COLOR_BUTTON_DESTRUCTIVE_FG)",
  "COLOR_BUTTON_GHOST_BG": "var(--COLOR_BUTTON_GHOST_BG)",
  "COLOR_BUTTON_GHOST_FG": "var(--COLOR_BUTTON_GHOST_FG)",
  "COLOR_STATUS_NEUTRAL_BG": "var(--COLOR_STATUS_NEUTRAL_BG)",
  "COLOR_STATUS_NEUTRAL_FG": "var(--COLOR_STATUS_NEUTRAL_FG)",
  "COLOR_STATUS_SUCCESS_BG": "var(--COLOR_STATUS_SUCCESS_BG)",
  "COLOR_STATUS_SUCCESS_FG": "var(--COLOR_STATUS_SUCCESS_FG)",
  "COLOR_STATUS_WARNING_BG": "var(--COLOR_STATUS_WARNING_BG)",
  "COLOR_STATUS_WARNING_FG": "var(--COLOR_STATUS_WARNING_FG)",
  "COLOR_STATUS_ERROR_BG": "var(--COLOR_STATUS_ERROR_BG)",
  "COLOR_STATUS_INFO_BG": "var(--COLOR_STATUS_INFO_BG)",
  "COLOR_STATUS_INFO_FG": "var(--COLOR_STATUS_INFO_FG)",
  "SPACING_0": "var(--SPACING_0)",
  "SPACING_1": "var(--SPACING_1)",
  "SPACING_2": "var(--SPACING_2)",
  "SPACING_3": "var(--SPACING_3)",
  "SPACING_4": "var(--SPACING_4)",
  "SPACING_5": "var(--SPACING_5)",
  "SPACING_6": "var(--SPACING_6)",
  "SPACING_7": "var(--SPACING_7)",
  "SPACING_8": "var(--SPACING_8)",
  "SPACING_9": "var(--SPACING_9)",
  "SPACING_10": "var(--SPACING_10)",
  "SPACING_11": "var(--SPACING_11)",
  "SPACING_12": "var(--SPACING_12)",
  "SPACING_13": "var(--SPACING_13)",
  "SPACING_14": "var(--SPACING_14)",
  "RADII_SM": "var(--RADII_SM)",
  "RADII_MD": "var(--RADII_MD)",
  "RADII_LG": "var(--RADII_LG)",
  "RADII_XL": "var(--RADII_XL)",
  "RADII_2XL": "var(--RADII_2XL)",
  "RADII_FULL": "var(--RADII_FULL)",
  "CARD": {
    "BACKGROUND": "var(--CARD-BACKGROUND)",
    "FOOTER": {
      "GAP": "var(--CARD-FOOTER-GAP)",
      "PADDING_TOP": "var(--CARD-FOOTER-PADDING_TOP)"
    },
    "GAP": "var(--CARD-GAP)",
    "PADDING": "var(--CARD-PADDING)",
    "RADIUS": "var(--CARD-RADIUS)"
  },
  "BUTTON": {
    "DESTRUCTIVE": {
      "BACKGROUND": "var(--BUTTON-DESTRUCTIVE-BACKGROUND)",
      "FOREGROUND": "var(--BUTTON-DESTRUCTIVE-FOREGROUND)"
    },
    "PRIMARY": {
      "BACKGROUND": "var(--BUTTON-PRIMARY-BACKGROUND)",
      "FOREGROUND": "var(--BUTTON-PRIMARY-FOREGROUND)"
    },
    "SECONDARY": {
      "BACKGROUND": "var(--BUTTON-SECONDARY-BACKGROUND)",
      "FOREGROUND": "var(--BUTTON-SECONDARY-FOREGROUND)"
    },
    "GHOST": {
      "BACKGROUND": "var(--BUTTON-GHOST-BACKGROUND)",
      "FOREGROUND": "var(--BUTTON-GHOST-FOREGROUND)"
    },
    "SIZE": {
      "SM": {
        "PADDING_Y": "var(--BUTTON-SIZE-SM-PADDING_Y)",
        "PADDING_X": "var(--BUTTON-SIZE-SM-PADDING_X)",
        "HEIGHT": "var(--BUTTON-SIZE-SM-HEIGHT)"
      },
      "DEFAULT": {
        "PADDING_Y": "var(--BUTTON-SIZE-DEFAULT-PADDING_Y)",
        "PADDING_X": "var(--BUTTON-SIZE-DEFAULT-PADDING_X)",
        "HEIGHT": "var(--BUTTON-SIZE-DEFAULT-HEIGHT)"
      },
      "LG": {
        "PADDING_Y": "var(--BUTTON-SIZE-LG-PADDING_Y)",
        "PADDING_X": "var(--BUTTON-SIZE-LG-PADDING_X)",
        "HEIGHT": "var(--BUTTON-SIZE-LG-HEIGHT)"
      }
    },
    "RADIUS": "var(--BUTTON-RADIUS)"
  },
  "STATUS": {
    "ERROR": {
      "FOREGROUND": "var(--STATUS-ERROR-FOREGROUND)",
      "BACKGROUND": "var(--STATUS-ERROR-BACKGROUND)"
    },
    "NEUTRAL": {
      "BACKGROUND": "var(--STATUS-NEUTRAL-BACKGROUND)",
      "FOREGROUND": "var(--STATUS-NEUTRAL-FOREGROUND)"
    },
    "SUCCESS": {
      "BACKGROUND": "var(--STATUS-SUCCESS-BACKGROUND)",
      "FOREGROUND": "var(--STATUS-SUCCESS-FOREGROUND)"
    },
    "WARNING": {
      "BACKGROUND": "var(--STATUS-WARNING-BACKGROUND)",
      "FOREGROUND": "var(--STATUS-WARNING-FOREGROUND)"
    },
    "INFO": {
      "BACKGROUND": "var(--STATUS-INFO-BACKGROUND)",
      "FOREGROUND": "var(--STATUS-INFO-FOREGROUND)"
    }
  }
} as const
