/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthorizeUser = {
  id: string;
  email: string;
  avatarUrl: string | null;
};

/** @internal */
export const AuthorizeUser$inboundSchema: z.ZodMiniType<
  AuthorizeUser,
  unknown
> = z.pipe(
  z.object({
    id: z.string(),
    email: z.string(),
    avatar_url: z.nullable(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "avatar_url": "avatarUrl",
    });
  }),
);

export function authorizeUserFromJSON(
  jsonString: string,
): SafeParseResult<AuthorizeUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthorizeUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthorizeUser' from JSON`,
  );
}
