/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const BenefitType = {
  Custom: "custom",
  Discord: "discord",
  GithubRepository: "github_repository",
  Downloadables: "downloadables",
  LicenseKeys: "license_keys",
  MeterCredit: "meter_credit",
} as const;
export type BenefitType = ClosedEnum<typeof BenefitType>;

/** @internal */
export const BenefitType$inboundSchema: z.ZodMiniEnum<typeof BenefitType> = z
  .enum(BenefitType);
/** @internal */
export const BenefitType$outboundSchema: z.ZodMiniEnum<typeof BenefitType> =
  BenefitType$inboundSchema;
