/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { BenefitType, BenefitType$inboundSchema } from "./benefittype.js";

export type BenefitGrantMetadata = {
  benefitId: string;
  benefitGrantId: string;
  benefitType: BenefitType;
};

/** @internal */
export const BenefitGrantMetadata$inboundSchema: z.ZodMiniType<
  BenefitGrantMetadata,
  unknown
> = z.pipe(
  z.object({
    benefit_id: z.string(),
    benefit_grant_id: z.string(),
    benefit_type: BenefitType$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "benefit_id": "benefitId",
      "benefit_grant_id": "benefitGrantId",
      "benefit_type": "benefitType",
    });
  }),
);

export function benefitGrantMetadataFromJSON(
  jsonString: string,
): SafeParseResult<BenefitGrantMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BenefitGrantMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BenefitGrantMetadata' from JSON`,
  );
}
