/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Additional metadata for a card payment method.
 */
export type CardPaymentMetadata = {
  /**
   * The brand of the card used for the payment.
   */
  brand: string;
  /**
   * The last 4 digits of the card number.
   */
  last4: string;
};

/** @internal */
export const CardPaymentMetadata$inboundSchema: z.ZodMiniType<
  CardPaymentMetadata,
  unknown
> = z.object({
  brand: z.string(),
  last4: z.string(),
});

export function cardPaymentMetadataFromJSON(
  jsonString: string,
): SafeParseResult<CardPaymentMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CardPaymentMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardPaymentMetadata' from JSON`,
  );
}
