/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const CheckoutLinkSortProperty = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  Label: "label",
  MinusLabel: "-label",
  SuccessUrl: "success_url",
  MinusSuccessUrl: "-success_url",
  AllowDiscountCodes: "allow_discount_codes",
  MinusAllowDiscountCodes: "-allow_discount_codes",
} as const;
export type CheckoutLinkSortProperty = ClosedEnum<
  typeof CheckoutLinkSortProperty
>;

/** @internal */
export const CheckoutLinkSortProperty$outboundSchema: z.ZodMiniEnum<
  typeof CheckoutLinkSortProperty
> = z.enum(CheckoutLinkSortProperty);
