/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CursorPagination = {
  hasNextPage: boolean;
};

/** @internal */
export const CursorPagination$inboundSchema: z.ZodMiniType<
  CursorPagination,
  unknown
> = z.pipe(
  z.object({
    has_next_page: z.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_next_page": "hasNextPage",
    });
  }),
);

export function cursorPaginationFromJSON(
  jsonString: string,
): SafeParseResult<CursorPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CursorPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CursorPagination' from JSON`,
  );
}
