/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  CustomerBenefitGrantGitHubRepositoryPropertiesUpdate,
  CustomerBenefitGrantGitHubRepositoryPropertiesUpdate$Outbound,
  CustomerBenefitGrantGitHubRepositoryPropertiesUpdate$outboundSchema,
} from "./customerbenefitgrantgithubrepositorypropertiesupdate.js";

export type CustomerBenefitGrantGitHubRepositoryUpdate = {
  benefitType: "github_repository";
  properties: CustomerBenefitGrantGitHubRepositoryPropertiesUpdate;
};

/** @internal */
export type CustomerBenefitGrantGitHubRepositoryUpdate$Outbound = {
  benefit_type: "github_repository";
  properties: CustomerBenefitGrantGitHubRepositoryPropertiesUpdate$Outbound;
};

/** @internal */
export const CustomerBenefitGrantGitHubRepositoryUpdate$outboundSchema:
  z.ZodMiniType<
    CustomerBenefitGrantGitHubRepositoryUpdate$Outbound,
    CustomerBenefitGrantGitHubRepositoryUpdate
  > = z.pipe(
    z.object({
      benefitType: z.literal("github_repository"),
      properties:
        CustomerBenefitGrantGitHubRepositoryPropertiesUpdate$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        benefitType: "benefit_type",
      });
    }),
  );

export function customerBenefitGrantGitHubRepositoryUpdateToJSON(
  customerBenefitGrantGitHubRepositoryUpdate:
    CustomerBenefitGrantGitHubRepositoryUpdate,
): string {
  return JSON.stringify(
    CustomerBenefitGrantGitHubRepositoryUpdate$outboundSchema.parse(
      customerBenefitGrantGitHubRepositoryUpdate,
    ),
  );
}
