/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DiscountDuration,
  DiscountDuration$inboundSchema,
  DiscountDuration$outboundSchema,
} from "./discountduration.js";
import {
  DiscountType,
  DiscountType$inboundSchema,
  DiscountType$outboundSchema,
} from "./discounttype.js";
import {
  MetadataOutputType,
  MetadataOutputType$inboundSchema,
  MetadataOutputType$Outbound,
  MetadataOutputType$outboundSchema,
} from "./metadataoutputtype.js";

export type DiscountPercentageOnceForeverDurationBase = {
  duration: DiscountDuration;
  type: DiscountType;
  /**
   * Discount percentage in basis points. A basis point is 1/100th of a percent. For example, 1000 basis points equals a 10% discount.
   */
  basisPoints: number;
  /**
   * Creation timestamp of the object.
   */
  createdAt: Date;
  /**
   * Last modification timestamp of the object.
   */
  modifiedAt: Date | null;
  /**
   * The ID of the object.
   */
  id: string;
  metadata: { [k: string]: MetadataOutputType };
  /**
   * Name of the discount. Will be displayed to the customer when the discount is applied.
   */
  name: string;
  /**
   * Code customers can use to apply the discount during checkout.
   */
  code: string | null;
  /**
   * Timestamp after which the discount is redeemable.
   */
  startsAt: Date | null;
  /**
   * Timestamp after which the discount is no longer redeemable.
   */
  endsAt: Date | null;
  /**
   * Maximum number of times the discount can be redeemed.
   */
  maxRedemptions: number | null;
  /**
   * Number of times the discount has been redeemed.
   */
  redemptionsCount: number;
  /**
   * The organization ID.
   */
  organizationId: string;
};

/** @internal */
export const DiscountPercentageOnceForeverDurationBase$inboundSchema:
  z.ZodMiniType<DiscountPercentageOnceForeverDurationBase, unknown> = z.pipe(
    z.object({
      duration: DiscountDuration$inboundSchema,
      type: DiscountType$inboundSchema,
      basis_points: z.int(),
      created_at: z.pipe(
        z.iso.datetime({ offset: true }),
        z.transform(v => new Date(v)),
      ),
      modified_at: z.nullable(
        z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
      ),
      id: z.string(),
      metadata: z.record(z.string(), MetadataOutputType$inboundSchema),
      name: z.string(),
      code: z.nullable(z.string()),
      starts_at: z.nullable(
        z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
      ),
      ends_at: z.nullable(
        z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
      ),
      max_redemptions: z.nullable(z.int()),
      redemptions_count: z.int(),
      organization_id: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "basis_points": "basisPoints",
        "created_at": "createdAt",
        "modified_at": "modifiedAt",
        "starts_at": "startsAt",
        "ends_at": "endsAt",
        "max_redemptions": "maxRedemptions",
        "redemptions_count": "redemptionsCount",
        "organization_id": "organizationId",
      });
    }),
  );
/** @internal */
export type DiscountPercentageOnceForeverDurationBase$Outbound = {
  duration: string;
  type: string;
  basis_points: number;
  created_at: string;
  modified_at: string | null;
  id: string;
  metadata: { [k: string]: MetadataOutputType$Outbound };
  name: string;
  code: string | null;
  starts_at: string | null;
  ends_at: string | null;
  max_redemptions: number | null;
  redemptions_count: number;
  organization_id: string;
};

/** @internal */
export const DiscountPercentageOnceForeverDurationBase$outboundSchema:
  z.ZodMiniType<
    DiscountPercentageOnceForeverDurationBase$Outbound,
    DiscountPercentageOnceForeverDurationBase
  > = z.pipe(
    z.object({
      duration: DiscountDuration$outboundSchema,
      type: DiscountType$outboundSchema,
      basisPoints: z.int(),
      createdAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
      modifiedAt: z.nullable(
        z.pipe(z.date(), z.transform(v => v.toISOString())),
      ),
      id: z.string(),
      metadata: z.record(z.string(), MetadataOutputType$outboundSchema),
      name: z.string(),
      code: z.nullable(z.string()),
      startsAt: z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
      endsAt: z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
      maxRedemptions: z.nullable(z.int()),
      redemptionsCount: z.int(),
      organizationId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        basisPoints: "basis_points",
        createdAt: "created_at",
        modifiedAt: "modified_at",
        startsAt: "starts_at",
        endsAt: "ends_at",
        maxRedemptions: "max_redemptions",
        redemptionsCount: "redemptions_count",
        organizationId: "organization_id",
      });
    }),
  );

export function discountPercentageOnceForeverDurationBaseToJSON(
  discountPercentageOnceForeverDurationBase:
    DiscountPercentageOnceForeverDurationBase,
): string {
  return JSON.stringify(
    DiscountPercentageOnceForeverDurationBase$outboundSchema.parse(
      discountPercentageOnceForeverDurationBase,
    ),
  );
}
export function discountPercentageOnceForeverDurationBaseFromJSON(
  jsonString: string,
): SafeParseResult<
  DiscountPercentageOnceForeverDurationBase,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DiscountPercentageOnceForeverDurationBase$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DiscountPercentageOnceForeverDurationBase' from JSON`,
  );
}
