/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const DiscountDuration = {
  Once: "once",
  Forever: "forever",
  Repeating: "repeating",
} as const;
export type DiscountDuration = ClosedEnum<typeof DiscountDuration>;

/** @internal */
export const DiscountDuration$inboundSchema: z.ZodMiniEnum<
  typeof DiscountDuration
> = z.enum(DiscountDuration);
/** @internal */
export const DiscountDuration$outboundSchema: z.ZodMiniEnum<
  typeof DiscountDuration
> = DiscountDuration$inboundSchema;
