/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const EventNamesSortProperty = {
  Name: "name",
  MinusName: "-name",
  Occurrences: "occurrences",
  MinusOccurrences: "-occurrences",
  FirstSeen: "first_seen",
  MinusFirstSeen: "-first_seen",
  LastSeen: "last_seen",
  MinusLastSeen: "-last_seen",
} as const;
export type EventNamesSortProperty = ClosedEnum<typeof EventNamesSortProperty>;

/** @internal */
export const EventNamesSortProperty$outboundSchema: z.ZodMiniEnum<
  typeof EventNamesSortProperty
> = z.enum(EventNamesSortProperty);
