/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Address, Address$inboundSchema } from "./address.js";
import {
  MetadataOutputType,
  MetadataOutputType$inboundSchema,
} from "./metadataoutputtype.js";
import { TaxIDFormat, TaxIDFormat$inboundSchema } from "./taxidformat.js";

export type LicenseKeyCustomerTaxId = string | TaxIDFormat;

export type LicenseKeyCustomer = {
  /**
   * The ID of the customer.
   */
  id: string;
  /**
   * Creation timestamp of the object.
   */
  createdAt: Date;
  /**
   * Last modification timestamp of the object.
   */
  modifiedAt: Date | null;
  metadata: { [k: string]: MetadataOutputType };
  /**
   * The ID of the customer in your system. This must be unique within the organization. Once set, it can't be updated.
   */
  externalId: string | null;
  /**
   * The email address of the customer. This must be unique within the organization.
   */
  email: string;
  /**
   * Whether the customer email address is verified. The address is automatically verified when the customer accesses the customer portal using their email address.
   */
  emailVerified: boolean;
  /**
   * The name of the customer.
   */
  name: string | null;
  billingAddress: Address | null;
  taxId: Array<string | TaxIDFormat | null> | null;
  /**
   * The ID of the organization owning the customer.
   */
  organizationId: string;
  /**
   * Timestamp for when the customer was soft deleted.
   */
  deletedAt: Date | null;
  avatarUrl: string;
};

/** @internal */
export const LicenseKeyCustomerTaxId$inboundSchema: z.ZodMiniType<
  LicenseKeyCustomerTaxId,
  unknown
> = z.union([z.string(), TaxIDFormat$inboundSchema]);

export function licenseKeyCustomerTaxIdFromJSON(
  jsonString: string,
): SafeParseResult<LicenseKeyCustomerTaxId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LicenseKeyCustomerTaxId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LicenseKeyCustomerTaxId' from JSON`,
  );
}

/** @internal */
export const LicenseKeyCustomer$inboundSchema: z.ZodMiniType<
  LicenseKeyCustomer,
  unknown
> = z.pipe(
  z.object({
    id: z.string(),
    created_at: z.pipe(
      z.iso.datetime({ offset: true }),
      z.transform(v => new Date(v)),
    ),
    modified_at: z.nullable(
      z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
    ),
    metadata: z.record(z.string(), MetadataOutputType$inboundSchema),
    external_id: z.nullable(z.string()),
    email: z.string(),
    email_verified: z.boolean(),
    name: z.nullable(z.string()),
    billing_address: z.nullable(Address$inboundSchema),
    tax_id: z.nullable(
      z.array(z.nullable(z.union([z.string(), TaxIDFormat$inboundSchema]))),
    ),
    organization_id: z.string(),
    deleted_at: z.nullable(
      z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
    ),
    avatar_url: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "modified_at": "modifiedAt",
      "external_id": "externalId",
      "email_verified": "emailVerified",
      "billing_address": "billingAddress",
      "tax_id": "taxId",
      "organization_id": "organizationId",
      "deleted_at": "deletedAt",
      "avatar_url": "avatarUrl",
    });
  }),
);

export function licenseKeyCustomerFromJSON(
  jsonString: string,
): SafeParseResult<LicenseKeyCustomer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LicenseKeyCustomer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LicenseKeyCustomer' from JSON`,
  );
}
