/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EventTypeWithStats,
  EventTypeWithStats$inboundSchema,
} from "./eventtypewithstats.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

export type ListResourceEventTypeWithStats = {
  items: Array<EventTypeWithStats>;
  pagination: Pagination;
};

/** @internal */
export const ListResourceEventTypeWithStats$inboundSchema: z.ZodMiniType<
  ListResourceEventTypeWithStats,
  unknown
> = z.object({
  items: z.array(EventTypeWithStats$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function listResourceEventTypeWithStatsFromJSON(
  jsonString: string,
): SafeParseResult<ListResourceEventTypeWithStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResourceEventTypeWithStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResourceEventTypeWithStats' from JSON`,
  );
}
