/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { MemberRole, MemberRole$outboundSchema } from "./memberrole.js";

/**
 * Schema for creating a new member.
 */
export type MemberCreate = {
  /**
   * The ID of the customer this member belongs to.
   */
  customerId: string;
  /**
   * The email address of the member.
   */
  email: string;
  name?: string | null | undefined;
  /**
   * The ID of the member in your system. This must be unique within the customer.
   */
  externalId?: string | null | undefined;
  role?: MemberRole | undefined;
};

/** @internal */
export type MemberCreate$Outbound = {
  customer_id: string;
  email: string;
  name?: string | null | undefined;
  external_id?: string | null | undefined;
  role?: string | undefined;
};

/** @internal */
export const MemberCreate$outboundSchema: z.ZodMiniType<
  MemberCreate$Outbound,
  MemberCreate
> = z.pipe(
  z.object({
    customerId: z.string(),
    email: z.string(),
    name: z.optional(z.nullable(z.string())),
    externalId: z.optional(z.nullable(z.string())),
    role: z.optional(MemberRole$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      customerId: "customer_id",
      externalId: "external_id",
    });
  }),
);

export function memberCreateToJSON(memberCreate: MemberCreate): string {
  return JSON.stringify(MemberCreate$outboundSchema.parse(memberCreate));
}
