/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MetricsIntervalLimit,
  MetricsIntervalLimit$inboundSchema,
} from "./metricsintervallimit.js";

/**
 * Date interval limits to get metrics for each interval.
 */
export type MetricsIntervalsLimits = {
  /**
   * Date interval limit to get metrics for a given interval.
   */
  hour: MetricsIntervalLimit;
  /**
   * Date interval limit to get metrics for a given interval.
   */
  day: MetricsIntervalLimit;
  /**
   * Date interval limit to get metrics for a given interval.
   */
  week: MetricsIntervalLimit;
  /**
   * Date interval limit to get metrics for a given interval.
   */
  month: MetricsIntervalLimit;
  /**
   * Date interval limit to get metrics for a given interval.
   */
  year: MetricsIntervalLimit;
};

/** @internal */
export const MetricsIntervalsLimits$inboundSchema: z.ZodMiniType<
  MetricsIntervalsLimits,
  unknown
> = z.object({
  hour: MetricsIntervalLimit$inboundSchema,
  day: MetricsIntervalLimit$inboundSchema,
  week: MetricsIntervalLimit$inboundSchema,
  month: MetricsIntervalLimit$inboundSchema,
  year: MetricsIntervalLimit$inboundSchema,
});

export function metricsIntervalsLimitsFromJSON(
  jsonString: string,
): SafeParseResult<MetricsIntervalsLimits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetricsIntervalsLimits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetricsIntervalsLimits' from JSON`,
  );
}
