/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const ProductBillingType = {
  OneTime: "one_time",
  Recurring: "recurring",
} as const;
export type ProductBillingType = ClosedEnum<typeof ProductBillingType>;

/** @internal */
export const ProductBillingType$outboundSchema: z.ZodMiniEnum<
  typeof ProductBillingType
> = z.enum(ProductBillingType);
