/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ProductPriceSeatTiers,
  ProductPriceSeatTiers$inboundSchema,
  ProductPriceSeatTiers$Outbound,
  ProductPriceSeatTiers$outboundSchema,
} from "./productpriceseattiers.js";
import {
  ProductPriceSource,
  ProductPriceSource$inboundSchema,
  ProductPriceSource$outboundSchema,
} from "./productpricesource.js";
import {
  ProductPriceType,
  ProductPriceType$inboundSchema,
  ProductPriceType$outboundSchema,
} from "./productpricetype.js";
import {
  SubscriptionRecurringInterval,
  SubscriptionRecurringInterval$inboundSchema,
  SubscriptionRecurringInterval$outboundSchema,
} from "./subscriptionrecurringinterval.js";

/**
 * A seat-based price for a product.
 */
export type ProductPriceSeatBased = {
  /**
   * Creation timestamp of the object.
   */
  createdAt: Date;
  /**
   * Last modification timestamp of the object.
   */
  modifiedAt: Date | null;
  /**
   * The ID of the price.
   */
  id: string;
  source: ProductPriceSource;
  amountType: "seat_based";
  /**
   * Whether the price is archived and no longer available.
   */
  isArchived: boolean;
  /**
   * The ID of the product owning the price.
   */
  productId: string;
  type: ProductPriceType;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  recurringInterval: SubscriptionRecurringInterval | null;
  /**
   * The currency.
   */
  priceCurrency: string;
  /**
   * List of pricing tiers for seat-based pricing.
   */
  seatTiers: ProductPriceSeatTiers;
};

/** @internal */
export const ProductPriceSeatBased$inboundSchema: z.ZodMiniType<
  ProductPriceSeatBased,
  unknown
> = z.pipe(
  z.object({
    created_at: z.pipe(
      z.iso.datetime({ offset: true }),
      z.transform(v => new Date(v)),
    ),
    modified_at: z.nullable(
      z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
    ),
    id: z.string(),
    source: ProductPriceSource$inboundSchema,
    amount_type: z.literal("seat_based"),
    is_archived: z.boolean(),
    product_id: z.string(),
    type: ProductPriceType$inboundSchema,
    recurring_interval: z.nullable(SubscriptionRecurringInterval$inboundSchema),
    price_currency: z.string(),
    seat_tiers: ProductPriceSeatTiers$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "modified_at": "modifiedAt",
      "amount_type": "amountType",
      "is_archived": "isArchived",
      "product_id": "productId",
      "recurring_interval": "recurringInterval",
      "price_currency": "priceCurrency",
      "seat_tiers": "seatTiers",
    });
  }),
);
/** @internal */
export type ProductPriceSeatBased$Outbound = {
  created_at: string;
  modified_at: string | null;
  id: string;
  source: string;
  amount_type: "seat_based";
  is_archived: boolean;
  product_id: string;
  type: string;
  recurring_interval: string | null;
  price_currency: string;
  seat_tiers: ProductPriceSeatTiers$Outbound;
};

/** @internal */
export const ProductPriceSeatBased$outboundSchema: z.ZodMiniType<
  ProductPriceSeatBased$Outbound,
  ProductPriceSeatBased
> = z.pipe(
  z.object({
    createdAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    modifiedAt: z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    id: z.string(),
    source: ProductPriceSource$outboundSchema,
    amountType: z.literal("seat_based"),
    isArchived: z.boolean(),
    productId: z.string(),
    type: ProductPriceType$outboundSchema,
    recurringInterval: z.nullable(SubscriptionRecurringInterval$outboundSchema),
    priceCurrency: z.string(),
    seatTiers: ProductPriceSeatTiers$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      createdAt: "created_at",
      modifiedAt: "modified_at",
      amountType: "amount_type",
      isArchived: "is_archived",
      productId: "product_id",
      recurringInterval: "recurring_interval",
      priceCurrency: "price_currency",
      seatTiers: "seat_tiers",
    });
  }),
);

export function productPriceSeatBasedToJSON(
  productPriceSeatBased: ProductPriceSeatBased,
): string {
  return JSON.stringify(
    ProductPriceSeatBased$outboundSchema.parse(productPriceSeatBased),
  );
}
export function productPriceSeatBasedFromJSON(
  jsonString: string,
): SafeParseResult<ProductPriceSeatBased, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductPriceSeatBased$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductPriceSeatBased' from JSON`,
  );
}
