/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const ProductPriceType = {
  OneTime: "one_time",
  Recurring: "recurring",
} as const;
export type ProductPriceType = ClosedEnum<typeof ProductPriceType>;

/** @internal */
export const ProductPriceType$inboundSchema: z.ZodMiniEnum<
  typeof ProductPriceType
> = z.enum(ProductPriceType);
/** @internal */
export const ProductPriceType$outboundSchema: z.ZodMiniEnum<
  typeof ProductPriceType
> = ProductPriceType$inboundSchema;
