/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type RefreshTokenRequest = {
  grantType: "refresh_token";
  clientId: string;
  clientSecret: string;
  refreshToken: string;
};

/** @internal */
export type RefreshTokenRequest$Outbound = {
  grant_type: "refresh_token";
  client_id: string;
  client_secret: string;
  refresh_token: string;
};

/** @internal */
export const RefreshTokenRequest$outboundSchema: z.ZodMiniType<
  RefreshTokenRequest$Outbound,
  RefreshTokenRequest
> = z.pipe(
  z.object({
    grantType: z.literal("refresh_token"),
    clientId: z.string(),
    clientSecret: z.string(),
    refreshToken: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      grantType: "grant_type",
      clientId: "client_id",
      clientSecret: "client_secret",
      refreshToken: "refresh_token",
    });
  }),
);

export function refreshTokenRequestToJSON(
  refreshTokenRequest: RefreshTokenRequest,
): string {
  return JSON.stringify(
    RefreshTokenRequest$outboundSchema.parse(refreshTokenRequest),
  );
}
