/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const RefundSortProperty = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  Amount: "amount",
  MinusAmount: "-amount",
} as const;
export type RefundSortProperty = ClosedEnum<typeof RefundSortProperty>;

/** @internal */
export const RefundSortProperty$outboundSchema: z.ZodMiniEnum<
  typeof RefundSortProperty
> = z.enum(RefundSortProperty);
