/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  SubscriptionProrationBehavior,
  SubscriptionProrationBehavior$outboundSchema,
} from "./subscriptionprorationbehavior.js";

export type SubscriptionUpdateProduct = {
  /**
   * Update subscription to another product.
   */
  productId: string;
  /**
   * Determine how to handle the proration billing. If not provided, will use the default organization setting.
   */
  prorationBehavior?: SubscriptionProrationBehavior | null | undefined;
};

/** @internal */
export type SubscriptionUpdateProduct$Outbound = {
  product_id: string;
  proration_behavior?: string | null | undefined;
};

/** @internal */
export const SubscriptionUpdateProduct$outboundSchema: z.ZodMiniType<
  SubscriptionUpdateProduct$Outbound,
  SubscriptionUpdateProduct
> = z.pipe(
  z.object({
    productId: z.string(),
    prorationBehavior: z.optional(
      z.nullable(SubscriptionProrationBehavior$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      productId: "product_id",
      prorationBehavior: "proration_behavior",
    });
  }),
);

export function subscriptionUpdateProductToJSON(
  subscriptionUpdateProduct: SubscriptionUpdateProduct,
): string {
  return JSON.stringify(
    SubscriptionUpdateProduct$outboundSchema.parse(subscriptionUpdateProduct),
  );
}
