/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const SubscriptionRecurringInterval = {
  Day: "day",
  Week: "week",
  Month: "month",
  Year: "year",
} as const;
export type SubscriptionRecurringInterval = ClosedEnum<
  typeof SubscriptionRecurringInterval
>;

/** @internal */
export const SubscriptionRecurringInterval$inboundSchema: z.ZodMiniEnum<
  typeof SubscriptionRecurringInterval
> = z.enum(SubscriptionRecurringInterval);
/** @internal */
export const SubscriptionRecurringInterval$outboundSchema: z.ZodMiniEnum<
  typeof SubscriptionRecurringInterval
> = SubscriptionRecurringInterval$inboundSchema;
