/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type SubscriptionUpdateTrial = {
  /**
   * Set or extend the trial period of the subscription. If set to `now`, the trial will end immediately.
   */
  trialEnd: Date;
};

/** @internal */
export type SubscriptionUpdateTrial$Outbound = {
  trial_end: string;
};

/** @internal */
export const SubscriptionUpdateTrial$outboundSchema: z.ZodMiniType<
  SubscriptionUpdateTrial$Outbound,
  SubscriptionUpdateTrial
> = z.pipe(
  z.object({
    trialEnd: z.pipe(z.date(), z.transform(v => v.toISOString())),
  }),
  z.transform((v) => {
    return remap$(v, {
      trialEnd: "trial_end",
    });
  }),
);

export function subscriptionUpdateTrialToJSON(
  subscriptionUpdateTrial: SubscriptionUpdateTrial,
): string {
  return JSON.stringify(
    SubscriptionUpdateTrial$outboundSchema.parse(subscriptionUpdateTrial),
  );
}
