/* tslint:disable */
/* eslint-disable */
/**
 * Polar API
 *  Welcome to the **Polar API** for [polar.sh](https://polar.sh).  The Public API is currently a [work in progress](https://github.com/polarsource/polar/issues/834) and is in active development. 🚀  #### Authentication  Use a [Personal Access Token](https://polar.sh/settings) and send it in the `Authorization` header on the format `Bearer [YOUR_TOKEN]`.  #### Feedback  If you have any feedback or comments, reach out in the [Polar API-issue](https://github.com/polarsource/polar/issues/834), or reach out on the Polar Discord server.  We\'d love to see what you\'ve built with the API and to get your thoughts on how we can make the API better!  #### Connecting  The Polar API is online at `https://api.polar.sh`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePledgePayLater
 */
export interface CreatePledgePayLater {
    /**
     * 
     * @type {string}
     * @memberof CreatePledgePayLater
     */
    issue_id: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePledgePayLater
     */
    amount: number;
}

/**
 * Check if a given object implements the CreatePledgePayLater interface.
 */
export function instanceOfCreatePledgePayLater(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "issue_id" in value;
    isInstance = isInstance && "amount" in value;

    return isInstance;
}

export function CreatePledgePayLaterFromJSON(json: any): CreatePledgePayLater {
    return CreatePledgePayLaterFromJSONTyped(json, false);
}

export function CreatePledgePayLaterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePledgePayLater {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'issue_id': json['issue_id'],
        'amount': json['amount'],
    };
}

export function CreatePledgePayLaterToJSON(value?: CreatePledgePayLater | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'issue_id': value.issue_id,
        'amount': value.amount,
    };
}

