/* tslint:disable */
/* eslint-disable */
/**
 * Polar API
 *  Welcome to the **Polar API** for [polar.sh](https://polar.sh).  The Public API is currently a [work in progress](https://github.com/polarsource/polar/issues/834) and is in active development. 🚀  #### Authentication  Use a [Personal Access Token](https://polar.sh/settings) and send it in the `Authorization` header on the format `Bearer [YOUR_TOKEN]`.  #### Feedback  If you have any feedback or comments, reach out in the [Polar API-issue](https://github.com/polarsource/polar/issues/834), or reach out on the Polar Discord server.  We\'d love to see what you\'ve built with the API and to get your thoughts on how we can make the API better!  #### Connecting  The Polar API is online at `https://api.polar.sh`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NotificationRead } from './NotificationRead';
import {
    NotificationReadFromJSON,
    NotificationReadFromJSONTyped,
    NotificationReadToJSON,
} from './NotificationRead';

/**
 * 
 * @export
 * @interface NotificationsList
 */
export interface NotificationsList {
    /**
     * 
     * @type {Array<NotificationRead>}
     * @memberof NotificationsList
     */
    notifications: Array<NotificationRead>;
    /**
     * 
     * @type {string}
     * @memberof NotificationsList
     */
    last_read_notification_id?: string;
}

/**
 * Check if a given object implements the NotificationsList interface.
 */
export function instanceOfNotificationsList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "notifications" in value;

    return isInstance;
}

export function NotificationsListFromJSON(json: any): NotificationsList {
    return NotificationsListFromJSONTyped(json, false);
}

export function NotificationsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationsList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notifications': ((json['notifications'] as Array<any>).map(NotificationReadFromJSON)),
        'last_read_notification_id': !exists(json, 'last_read_notification_id') ? undefined : json['last_read_notification_id'],
    };
}

export function NotificationsListToJSON(value?: NotificationsList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notifications': ((value.notifications as Array<any>).map(NotificationReadToJSON)),
        'last_read_notification_id': value.last_read_notification_id,
    };
}

