/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CustomerMetersGetRequest = {
  /**
   * The customer meter ID.
   */
  id: string;
};

/** @internal */
export type CustomerMetersGetRequest$Outbound = {
  id: string;
};

/** @internal */
export const CustomerMetersGetRequest$outboundSchema: z.ZodMiniType<
  CustomerMetersGetRequest$Outbound,
  CustomerMetersGetRequest
> = z.object({
  id: z.string(),
});

export function customerMetersGetRequestToJSON(
  customerMetersGetRequest: CustomerMetersGetRequest,
): string {
  return JSON.stringify(
    CustomerMetersGetRequest$outboundSchema.parse(customerMetersGetRequest),
  );
}
