/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CustomersGetStateExternalRequest = {
  /**
   * The customer external ID.
   */
  externalId: string;
};

/** @internal */
export type CustomersGetStateExternalRequest$Outbound = {
  external_id: string;
};

/** @internal */
export const CustomersGetStateExternalRequest$outboundSchema: z.ZodMiniType<
  CustomersGetStateExternalRequest$Outbound,
  CustomersGetStateExternalRequest
> = z.pipe(
  z.object({
    externalId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      externalId: "external_id",
    });
  }),
);

export function customersGetStateExternalRequestToJSON(
  customersGetStateExternalRequest: CustomersGetStateExternalRequest,
): string {
  return JSON.stringify(
    CustomersGetStateExternalRequest$outboundSchema.parse(
      customersGetStateExternalRequest,
    ),
  );
}
