/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CustomerSeatsRevokeSeatRequest = {
  seatId: string;
};

/** @internal */
export type CustomerSeatsRevokeSeatRequest$Outbound = {
  seat_id: string;
};

/** @internal */
export const CustomerSeatsRevokeSeatRequest$outboundSchema: z.ZodMiniType<
  CustomerSeatsRevokeSeatRequest$Outbound,
  CustomerSeatsRevokeSeatRequest
> = z.pipe(
  z.object({
    seatId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      seatId: "seat_id",
    });
  }),
);

export function customerSeatsRevokeSeatRequestToJSON(
  customerSeatsRevokeSeatRequest: CustomerSeatsRevokeSeatRequest,
): string {
  return JSON.stringify(
    CustomerSeatsRevokeSeatRequest$outboundSchema.parse(
      customerSeatsRevokeSeatRequest,
    ),
  );
}
