/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CustomerPortalOrdersGenerateInvoiceSecurity = {
  customerSession: string;
};

export type CustomerPortalOrdersGenerateInvoiceRequest = {
  /**
   * The order ID.
   */
  id: string;
};

/** @internal */
export type CustomerPortalOrdersGenerateInvoiceSecurity$Outbound = {
  customer_session: string;
};

/** @internal */
export const CustomerPortalOrdersGenerateInvoiceSecurity$outboundSchema:
  z.ZodMiniType<
    CustomerPortalOrdersGenerateInvoiceSecurity$Outbound,
    CustomerPortalOrdersGenerateInvoiceSecurity
  > = z.pipe(
    z.object({
      customerSession: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        customerSession: "customer_session",
      });
    }),
  );

export function customerPortalOrdersGenerateInvoiceSecurityToJSON(
  customerPortalOrdersGenerateInvoiceSecurity:
    CustomerPortalOrdersGenerateInvoiceSecurity,
): string {
  return JSON.stringify(
    CustomerPortalOrdersGenerateInvoiceSecurity$outboundSchema.parse(
      customerPortalOrdersGenerateInvoiceSecurity,
    ),
  );
}

/** @internal */
export type CustomerPortalOrdersGenerateInvoiceRequest$Outbound = {
  id: string;
};

/** @internal */
export const CustomerPortalOrdersGenerateInvoiceRequest$outboundSchema:
  z.ZodMiniType<
    CustomerPortalOrdersGenerateInvoiceRequest$Outbound,
    CustomerPortalOrdersGenerateInvoiceRequest
  > = z.object({
    id: z.string(),
  });

export function customerPortalOrdersGenerateInvoiceRequestToJSON(
  customerPortalOrdersGenerateInvoiceRequest:
    CustomerPortalOrdersGenerateInvoiceRequest,
): string {
  return JSON.stringify(
    CustomerPortalOrdersGenerateInvoiceRequest$outboundSchema.parse(
      customerPortalOrdersGenerateInvoiceRequest,
    ),
  );
}
