/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  CustomFieldUpdate,
  CustomFieldUpdate$Outbound,
  CustomFieldUpdate$outboundSchema,
} from "../components/customfieldupdate.js";

export type CustomFieldsUpdateRequest = {
  /**
   * The custom field ID.
   */
  id: string;
  customFieldUpdate: CustomFieldUpdate;
};

/** @internal */
export type CustomFieldsUpdateRequest$Outbound = {
  id: string;
  CustomFieldUpdate: CustomFieldUpdate$Outbound;
};

/** @internal */
export const CustomFieldsUpdateRequest$outboundSchema: z.ZodMiniType<
  CustomFieldsUpdateRequest$Outbound,
  CustomFieldsUpdateRequest
> = z.pipe(
  z.object({
    id: z.string(),
    customFieldUpdate: CustomFieldUpdate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      customFieldUpdate: "CustomFieldUpdate",
    });
  }),
);

export function customFieldsUpdateRequestToJSON(
  customFieldsUpdateRequest: CustomFieldsUpdateRequest,
): string {
  return JSON.stringify(
    CustomFieldsUpdateRequest$outboundSchema.parse(customFieldsUpdateRequest),
  );
}
