/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CustomerPortalCustomersConfirmPaymentMethodSecurity = {
  customerSession: string;
};

/** @internal */
export type CustomerPortalCustomersConfirmPaymentMethodSecurity$Outbound = {
  customer_session: string;
};

/** @internal */
export const CustomerPortalCustomersConfirmPaymentMethodSecurity$outboundSchema:
  z.ZodMiniType<
    CustomerPortalCustomersConfirmPaymentMethodSecurity$Outbound,
    CustomerPortalCustomersConfirmPaymentMethodSecurity
  > = z.pipe(
    z.object({
      customerSession: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        customerSession: "customer_session",
      });
    }),
  );

export function customerPortalCustomersConfirmPaymentMethodSecurityToJSON(
  customerPortalCustomersConfirmPaymentMethodSecurity:
    CustomerPortalCustomersConfirmPaymentMethodSecurity,
): string {
  return JSON.stringify(
    CustomerPortalCustomersConfirmPaymentMethodSecurity$outboundSchema.parse(
      customerPortalCustomersConfirmPaymentMethodSecurity,
    ),
  );
}
