/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  ListResourceMember,
  ListResourceMember$inboundSchema,
} from "../components/listresourcemember.js";
import {
  MemberSortProperty,
  MemberSortProperty$outboundSchema,
} from "../components/membersortproperty.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MembersListMembersRequest = {
  /**
   * Filter by customer ID.
   */
  customerId?: string | null | undefined;
  /**
   * Page number, defaults to 1.
   */
  page?: number | undefined;
  /**
   * Size of a page, defaults to 10. Maximum is 100.
   */
  limit?: number | undefined;
  /**
   * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
   */
  sorting?: Array<MemberSortProperty> | null | undefined;
};

export type MembersListMembersResponse = {
  result: ListResourceMember;
};

/** @internal */
export type MembersListMembersRequest$Outbound = {
  customer_id?: string | null | undefined;
  page: number;
  limit: number;
  sorting?: Array<string> | null | undefined;
};

/** @internal */
export const MembersListMembersRequest$outboundSchema: z.ZodMiniType<
  MembersListMembersRequest$Outbound,
  MembersListMembersRequest
> = z.pipe(
  z.object({
    customerId: z.optional(z.nullable(z.string())),
    page: z._default(z.int(), 1),
    limit: z._default(z.int(), 10),
    sorting: z.optional(z.nullable(z.array(MemberSortProperty$outboundSchema))),
  }),
  z.transform((v) => {
    return remap$(v, {
      customerId: "customer_id",
    });
  }),
);

export function membersListMembersRequestToJSON(
  membersListMembersRequest: MembersListMembersRequest,
): string {
  return JSON.stringify(
    MembersListMembersRequest$outboundSchema.parse(membersListMembersRequest),
  );
}

/** @internal */
export const MembersListMembersResponse$inboundSchema: z.ZodMiniType<
  MembersListMembersResponse,
  unknown
> = z.pipe(
  z.object({
    Result: ListResourceMember$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function membersListMembersResponseFromJSON(
  jsonString: string,
): SafeParseResult<MembersListMembersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MembersListMembersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MembersListMembersResponse' from JSON`,
  );
}
