/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  OrganizationUpdate,
  OrganizationUpdate$Outbound,
  OrganizationUpdate$outboundSchema,
} from "../components/organizationupdate.js";

export type OrganizationsUpdateRequest = {
  id: string;
  organizationUpdate: OrganizationUpdate;
};

/** @internal */
export type OrganizationsUpdateRequest$Outbound = {
  id: string;
  OrganizationUpdate: OrganizationUpdate$Outbound;
};

/** @internal */
export const OrganizationsUpdateRequest$outboundSchema: z.ZodMiniType<
  OrganizationsUpdateRequest$Outbound,
  OrganizationsUpdateRequest
> = z.pipe(
  z.object({
    id: z.string(),
    organizationUpdate: OrganizationUpdate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationUpdate: "OrganizationUpdate",
    });
  }),
);

export function organizationsUpdateRequestToJSON(
  organizationsUpdateRequest: OrganizationsUpdateRequest,
): string {
  return JSON.stringify(
    OrganizationsUpdateRequest$outboundSchema.parse(organizationsUpdateRequest),
  );
}
