/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  SubscriptionUpdate,
  SubscriptionUpdate$Outbound,
  SubscriptionUpdate$outboundSchema,
} from "../components/subscriptionupdate.js";

export type SubscriptionsUpdateRequest = {
  /**
   * The subscription ID.
   */
  id: string;
  subscriptionUpdate: SubscriptionUpdate;
};

/** @internal */
export type SubscriptionsUpdateRequest$Outbound = {
  id: string;
  SubscriptionUpdate: SubscriptionUpdate$Outbound;
};

/** @internal */
export const SubscriptionsUpdateRequest$outboundSchema: z.ZodMiniType<
  SubscriptionsUpdateRequest$Outbound,
  SubscriptionsUpdateRequest
> = z.pipe(
  z.object({
    id: z.string(),
    subscriptionUpdate: SubscriptionUpdate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      subscriptionUpdate: "SubscriptionUpdate",
    });
  }),
);

export function subscriptionsUpdateRequestToJSON(
  subscriptionsUpdateRequest: SubscriptionsUpdateRequest,
): string {
  return JSON.stringify(
    SubscriptionsUpdateRequest$outboundSchema.parse(subscriptionsUpdateRequest),
  );
}
