version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      # args:
      #   # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
      #   # Append -bullseye or -buster to pin to an OS version.
      #   # Use -bullseye variants on local arm64/Apple Silicon.
      #   VARIANT: 3-bullseye
      #   # Optional Node.js version to install
      #   NODE_VERSION: "lts/*"

    volumes:
      - ..:/workspace:cached
      - venv:/workspace/server/.venv:rw # do not mount from host

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis

  db:
    image: postgres:15.1-bullseye
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: polar
      POSTGRES_DB: polar
      POSTGRES_PASSWORD: polar
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-q", "-d", "polar", "-U", "polar"]
    #   timeout: 40s
    #   interval: 2s
    #   retries: 20

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data: {}
  venv: {}
