import { problem } from './mockFactories'
import type { MockSubscriptionRecord } from './mockTypes'

export const problemSubscriptions: MockSubscriptionRecord[] = [
  problem({
    id: 'sub_problem_missing_country',
    customerLabel: 'Uma NoCountry',
    emailLocal: 'uma.nocountry',
    productName: 'Pro',
    amountCents: 1900,
    category: 'customer',
    status: 'action_required',
    issueCode: 'customer_missing_country',
    title: 'Customer missing billing country',
    detail:
      'No billing country. Confirm it before the first renewal so tax is correct.',
    recommendedAction: 'Confirm the billing country, then re-run precheck.',
  }),
  problem({
    id: 'sub_problem_existing_product',
    customerLabel: 'Vince Mapped',
    emailLocal: 'vince.mapped',
    productName: 'Pro',
    amountCents: 1900,
    category: 'product',
    status: 'action_required',
    issueCode: 'product_exists_in_polar',
    title: 'Existing Polar product mapping',
    detail:
      'A Polar product already uses this name. Importing without a mapping choice risks a duplicate catalog entry.',
    recommendedAction: 'Map Stripe Pro to the existing Polar Pro product.',
  }),
  problem({
    id: 'sub_problem_identity_conflict',
    customerLabel: 'Wendy Conflict',
    emailLocal: 'wendy.shared',
    productName: 'Starter',
    amountCents: 900,
    category: 'identity',
    status: 'action_required',
    issueCode: 'customer_stripe_id_conflict',
    title: 'Customer identity conflict',
    detail:
      'A Polar customer with this email already has a different Stripe id. Reconcile them manually; this customer stays on the source.',
    recommendedAction:
      'Merge or reconcile the customer identity, then re-import.',
  }),
  problem({
    id: 'sub_problem_missing_payment_method',
    customerLabel: 'Xander Cardless',
    emailLocal: 'xander.cardless',
    productName: 'Pro',
    amountCents: 1900,
    category: 'payment',
    status: 'cutover_hold',
    issueCode: 'missing_payment_method',
    title: 'Missing payment method',
    detail:
      'No copied card has landed on Polar for this customer yet. They need to enter billing details again, or the copy has to pick them up.',
    recommendedAction: 'Ask the customer to add a card, or retry card copy.',
  }),
  problem({
    id: 'sub_problem_expired_card',
    customerLabel: 'Yara Expired',
    emailLocal: 'yara.expired',
    productName: 'Team',
    amountCents: 4900,
    category: 'payment',
    status: 'cutover_hold',
    issueCode: 'expired_card',
    title: 'Expired card on file',
    detail:
      'The copied card has expired, so the first Polar renewal will fail and go to dunning.',
    recommendedAction: 'Ask the customer to enter a new payment method.',
  }),
  problem({
    id: 'sub_problem_cancel_at_period_end',
    customerLabel: 'Zane Ending',
    emailLocal: 'zane.ending',
    productName: 'Pro',
    amountCents: 1900,
    category: 'lifecycle',
    status: 'blocked',
    issueCode: 'cancel_at_period_end',
    title: 'Cancelling at period end',
    detail:
      "It's set to cancel at the end of the period on the source, so there is no renewal for Polar to take over.",
    recommendedAction:
      'Leave on Stripe until it ends, or ask the customer to resume.',
  }),
  problem({
    id: 'sub_problem_multiple_line_items',
    customerLabel: 'Ada Bundle',
    emailLocal: 'ada.bundle',
    productName: 'Pro + Add-on',
    amountCents: 2800,
    planLabel: 'Multi-item · $28/mo',
    category: 'pricing',
    status: 'blocked',
    issueCode: 'multiple_line_items',
    title: 'Multiple line items',
    detail:
      'Stripe subscription has more than one line item. Polar imports a single price per subscription.',
    recommendedAction:
      'Split or simplify the Stripe subscription, then re-assess.',
  }),
  problem({
    id: 'sub_problem_quantity',
    customerLabel: 'Beau Seats',
    emailLocal: 'beau.seats',
    productName: 'Team',
    amountCents: 24500,
    planLabel: 'Team × 5 · $245/mo',
    category: 'pricing',
    status: 'blocked',
    issueCode: 'unsupported_quantity',
    title: 'Quantity greater than one',
    detail:
      'Seat quantity is greater than 1. Polar does not import multi-quantity Stripe items in this path yet.',
    recommendedAction:
      'Keep on Stripe or remodel as seat-based Polar pricing later.',
  }),
  problem({
    id: 'sub_problem_discount',
    customerLabel: 'Cleo Coupon',
    emailLocal: 'cleo.coupon',
    productName: 'Pro',
    amountCents: 1900,
    planLabel: 'Pro · $19/mo (−20%)',
    category: 'pricing',
    status: 'action_required',
    issueCode: 'subscription_has_discount',
    title: 'Active discount',
    detail:
      'A discount or coupon is attached. Importing at list price would overcharge the customer.',
    recommendedAction: 'Remove or honor the discount before transferring.',
  }),
  problem({
    id: 'sub_problem_manual_invoice',
    customerLabel: 'Drew Invoice',
    emailLocal: 'drew.invoice',
    productName: 'Enterprise',
    amountCents: 19900,
    planLabel: 'Enterprise · send_invoice',
    category: 'pricing',
    status: 'action_required',
    issueCode: 'send_invoice_collection',
    title: 'Manual invoice collection',
    detail:
      'Collection method is send_invoice. Polar cutover expects charge_automatically with a card.',
    recommendedAction:
      'Switch to automatic charging or keep billing on Stripe.',
  }),
  problem({
    id: 'sub_problem_past_due',
    customerLabel: 'Eden PastDue',
    emailLocal: 'eden.pastdue',
    productName: 'Pro',
    amountCents: 1900,
    category: 'lifecycle',
    status: 'blocked',
    issueCode: 'subscription_not_importable',
    title: 'Past due on Stripe',
    detail:
      'Source status is past_due. Polar only takes over healthy active or trialing subscriptions.',
    recommendedAction: 'Recover payment on Stripe, then re-assess for cutover.',
  }),
  problem({
    id: 'sub_problem_missing_email',
    customerLabel: 'No Email Customer',
    emailLocal: null,
    productName: 'Starter',
    amountCents: 900,
    category: 'customer',
    status: 'action_required',
    issueCode: 'customer_missing_email',
    title: 'Customer missing email',
    detail:
      "The source customer has no email, so it can't be imported into Polar.",
    recommendedAction:
      'Add an email on the Stripe customer, then re-run precheck.',
  }),
  problem({
    id: 'sub_problem_renewal_window',
    customerLabel: 'Finn Renewing',
    emailLocal: 'finn.renewing',
    productName: 'Pro',
    amountCents: 1900,
    category: 'cutover',
    status: 'cutover_hold',
    issueCode: 'renewal_inside_safety_window',
    title: 'Renewal inside 24 hours',
    detail:
      'It renews on the source too soon to hand over without risking a double charge.',
    recommendedAction: 'Retry cutover after that renewal has gone through.',
  }),
  problem({
    id: 'sub_problem_plan_changed',
    customerLabel: 'Gina Upgraded',
    emailLocal: 'gina.upgraded',
    productName: 'Team',
    amountCents: 4900,
    category: 'cutover',
    status: 'cutover_hold',
    issueCode: 'plan_changed_after_assessment',
    title: 'Plan changed after assessment',
    detail:
      'The plan changed on the source since the import, so the imported subscription no longer matches.',
    recommendedAction:
      'Re-run the import for this customer, then retry cutover.',
  }),
  problem({
    id: 'sub_problem_existing_polar_sub',
    customerLabel: 'Hugo Duplicate',
    emailLocal: 'hugo.duplicate',
    productName: 'Pro',
    amountCents: 1900,
    category: 'cutover',
    status: 'blocked',
    issueCode: 'customer_already_subscribed',
    title: 'Existing active Polar subscription',
    detail:
      'This customer already has a live subscription to the product on Polar, so a duplicate is not created.',
    recommendedAction:
      'Leave the Stripe copy on Stripe or cancel one side deliberately.',
  }),
  problem({
    id: 'sub_problem_payment_reentry',
    customerLabel: 'Ivy LinkPay',
    emailLocal: 'ivy.linkpay',
    productName: 'Starter',
    amountCents: 900,
    category: 'payment',
    status: 'action_required',
    issueCode: 'payment_method_requires_reentry',
    title: 'Payment method requires re-entry',
    detail:
      'Payment method (link) cannot be copied. Ask the customer to re-enter their billing details.',
    recommendedAction:
      'Send a Polar update-payment link before including them in a transfer.',
  }),
]
