# https://just.systems

install:
    uv sync --all-extras

lint:
    uv run ruff format .
    uv run ruff check --fix .
    uv run ty check .

lint-check:
    uv run ruff format --check .
    uv run ruff check .
    uv run ty check .

test:
    uv run pytest tests/

openapi:
  uv run -m --directory ../../server scripts.generate_openapi | jq -r > openapi.json

generate language:
  uv run -m cli --language {{language}} --clear openapi.json ../{{language}}
