import type { ModelDefinition } from "../models";

export const alibabaModels = [
	{
		id: "qwen-plus",
		name: "Qwen Plus",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-plus",
				inputPrice: 0.4 / 1e6,
				outputPrice: 4.0 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "qwen-turbo",
		name: "Qwen Turbo",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-turbo",
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.2 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "qwen3-coder-plus",
		name: "Qwen3 Coder Plus",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen3-coder-plus",
				inputPrice: 6 / 1e6,
				outputPrice: 60 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 66000,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "qwen-qwq-32b",
		name: "Qwen QwQ 32B",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/QwQ-32B",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.45 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "qwen3-235b-a22b",
		name: "Qwen3 235B A22B",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-235B-A22B",
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "qwen3-14b",
		name: "Qwen3 14B",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-14B",
				inputPrice: 0.08 / 1e6,
				outputPrice: 0.24 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "qwen3-32b",
		name: "Qwen3 32B",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-32B",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "qwen3-30b-a3b",
		name: "Qwen3 30B A3B",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-30B-A3B",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "qwen25-coder-7b",
		name: "Qwen2.5 Coder 7B",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2.5-Coder-7B",
				inputPrice: 0.01 / 1e6,
				outputPrice: 0.03 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "qwen25-32b-instruct",
		name: "Qwen2.5 32B Instruct",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2.5-32B-Instruct",
				inputPrice: 0.06 / 1e6,
				outputPrice: 0.2 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "qwen25-72b-instruct",
		name: "Qwen2.5 72B Instruct",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2.5-72B-Instruct",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "qwen2-vl-72b-instruct",
		name: "Qwen2 VL 72B Instruct",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2-VL-72B-Instruct",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "qwen2-5-vl-72b-instruct",
		name: "Qwen2.5 VL 72B Instruct",
		family: "alibaba",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2.5-VL-72B-Instruct",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: false,
			},
		],
		jsonOutput: true,
	},
] as const satisfies ModelDefinition[];