import type { ModelDefinition } from "../models";

export const anthropicModels = [
	{
		id: "claude-3-7-sonnet",
		name: "Claude 3.7 Sonnet",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-3-7-sonnet-latest",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-3-7-sonnet-20250219",
		name: "Claude 3.7 Sonnet (2025-02-19)",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-3-7-sonnet-20250219",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				reasoning: true,
				tools: true,
			},
		],
	},
	{
		id: "claude-3-5-sonnet-20241022",
		name: "Claude 3.5 Sonnet (2024-10-22)",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-3-5-sonnet-20241022",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-2.1",
		name: "Claude 2.1",
		family: "anthropic",
		deprecatedAt: new Date("2025-06-15T00:00:00Z"),
		deactivatedAt: new Date("2025-07-21T16:00:00Z"),
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-2.1",
				inputPrice: 8.0 / 1e6,
				outputPrice: 24.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
	},
	{
		id: "claude-sonnet-4-20250514",
		name: "Claude Sonnet 4 (2025-05-14)",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-sonnet-4-20250514",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-opus-4-20250514",
		name: "Claude Opus 4 (2025-05-14)",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-opus-4-20250514",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-opus-4-1",
		name: "Claude Opus 4.1",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-opus-4-1",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				cachedInputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				reasoning: true,
				tools: true,
			},
		],
	},
	{
		id: "claude-3-5-sonnet",
		name: "Claude 3.5 Sonnet",
		family: "anthropic",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-3-5-sonnet-latest",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
] as const satisfies ModelDefinition[];