import type { ModelDefinition } from "../models";

export const deepseekModels = [
	{
		id: "deepseek-v3",
		name: "DeepSeek V3",
		family: "deepseek",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "cloudrift",
				modelName: "deepseek-ai/DeepSeek-V3",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 163840,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
			{
				providerId: "deepseek",
				modelName: "deepseek-chat",
				inputPrice: 0.27 / 1e6,
				outputPrice: 1.1 / 1e6,
				requestPrice: 0,
				contextSize: 64000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
			{
				providerId: "nebius",
				modelName: "deepseek-ai/DeepSeek-V3",
				inputPrice: 0.5 / 1e6,
				outputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 64000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: false,
	},
	{
		id: "deepseek-r1",
		name: "DeepSeek R1",
		family: "deepseek",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "cloudrift",
				modelName: "deepseek-ai/DeepSeek-R1",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 163840,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
			{
				providerId: "deepseek",
				modelName: "deepseek-reasoner",
				inputPrice: 0.55 / 1e6,
				outputPrice: 2.19 / 1e6,
				requestPrice: 0,
				contextSize: 64000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
			{
				providerId: "nebius",
				modelName: "deepseek-ai/DeepSeek-R1",
				inputPrice: 0.8 / 1e6,
				outputPrice: 2.4 / 1e6,
				requestPrice: 0,
				contextSize: 64000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: false,
	},
	{
		id: "deepseek-r1-0528",
		name: "DeepSeek R1 (0528)",
		family: "deepseek",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "cloudrift",
				modelName: "deepseek-ai/DeepSeek-R1-0528",
				inputPrice: 0.25 / 1e6,
				outputPrice: 1 / 1e6,
				requestPrice: 0,
				contextSize: 32770,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
			{
				providerId: "deepseek",
				modelName: "deepseek-reasoner",
				inputPrice: 0.55 / 1e6,
				outputPrice: 2.19 / 1e6,
				requestPrice: 0,
				contextSize: 64000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
			// TODO mark as unstable
			// {
			// 	providerId: "nebius",
			// 	modelName: "deepseek-ai/DeepSeek-R1-0528",
			// 	inputPrice: 0.8 / 1e6,
			// 	outputPrice: 2.4 / 1e6,
			// 	requestPrice: 0,
			// 	contextSize: 64000,
			// 	maxOutput: undefined,
			// 	streaming: true,
			// 	vision: false,
			// 	tools: false,
			// },
		],
		jsonOutput: false,
	},
	{
		id: "deepseek-r1-distill-llama-70b",
		name: "DeepSeek R1 Distill Llama 70B",
		family: "deepseek",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "groq",
				modelName: "deepseek-r1-distill-llama-70b",
				inputPrice: 0.75 / 1e6,
				outputPrice: 0.99 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
			{
				providerId: "nebius",
				modelName: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
				inputPrice: 0.25 / 1e6,
				outputPrice: 0.75 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
] as const satisfies ModelDefinition[];