import type { ModelDefinition } from "../models";

export const metaModels = [
	{
		id: "llama-3.1-8b-instruct",
		name: "Llama 3.1 8B Instruct",
		family: "meta",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "meta-llama/Meta-Llama-3.1-8B-Instruct",
				inputPrice: 0.02 / 1e6,
				outputPrice: 0.06 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
			{
				providerId: "inference.net",
				modelName: "meta-llama/llama-3.1-8b-instruct/fp-8",
				inputPrice: 0.07 / 1e6,
				outputPrice: 0.33 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
			{
				providerId: "together.ai",
				modelName: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
				inputPrice: 0.06 / 1e6,
				outputPrice: 0.06 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "llama-3.1-70b-instruct-free",
		name: "Meta Llama 3.1 70B Instruct FP8 (Free)",
		family: "meta",
		free: true,
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "cloudrift",
				modelName: "meta-llama/Meta-Llama-3.1-70B-Instruct-FP8",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0,
				contextSize: 16380,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
	},
	{
		id: "llama-3.2-11b-instruct",
		name: "Llama 3.2 11B Instruct",
		family: "meta",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "inference.net",
				modelName: "meta-llama/llama-3.2-11b-instruct/fp-16",
				inputPrice: 0.07 / 1e6,
				outputPrice: 0.33 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
	},
	{
		id: "llama-4-maverick-17b-128e-instruct",
		name: "Llama 4 Maverick 17B 128E Instruct",
		family: "meta",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "cloudrift",
				modelName: "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.35 / 1e6,
				requestPrice: 0,
				contextSize: 1_050_000,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
	},
	{
		id: "llama-3.1-nemotron-ultra-253b",
		name: "Llama 3.1 Nemotron Ultra 253B",
		family: "meta",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "nvidia/Llama-3_1-Nemotron-Ultra-253B-v1",
				inputPrice: 0.6 / 1e6,
				outputPrice: 1.8 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "llama-3.3-nemotron-super-498",
		name: "Llama 3.3 Nemotron Super 498",
		family: "meta",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "nvidia/Llama-3_3-Nemotron-Super-49B-v1",
				inputPrice: 0.6 / 1e6,
				outputPrice: 1.8 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "llama-guard-4-12b",
		name: "Llama Guard 4 12B",
		family: "meta",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "groq",
				modelName: "meta-llama/llama-guard-4-12b",
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.2 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "llama-3.3-70b-instruct",
		name: "Llama 3.3 70B Instruct",
		family: "meta",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "meta-llama/Llama-3.3-70B-Instruct",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "llama-3.1-405b-instruct",
		name: "Llama 3.1 405B Instruct",
		family: "meta",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "meta-llama/Meta-Llama-3.1-405B-Instruct",
				inputPrice: 1.0 / 1e6,
				outputPrice: 3.0 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	// {
	// 	id: "llama-guard-3-8b",
	// 	name: "Llama Guard 3 8B",
	// 	family: "meta",
	// 	deprecatedAt: undefined,
	// 	deactivatedAt: undefined,
	// 	providers: [
	// 		{
	// 			providerId: "nebius",
	// 			test: "only",
	// 			modelName: "meta-llama/Llama-Guard-3-8B",
	// 			inputPrice: 0.02 / 1e6,
	// 			outputPrice: 0.06 / 1e6,
	// 			requestPrice: 0,
	// 			contextSize: 8192,
	// 			maxOutput: undefined,
	// 			streaming: true,
	// 			vision: false,
	// 			tools: false,
	// 		},
	// 	],
	// 	jsonOutput: false,
	// },
	{
		id: "openbio-llama3-70b",
		name: "OpenBio Llama3 70B",
		family: "meta",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "aaditya/Llama3-OpenBioLLM-70B",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "llama-4-scout",
		name: "Llama 4 Scout",
		family: "meta",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "together.ai",
				modelName: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
				inputPrice: 0.18 / 1e6,
				outputPrice: 0.59 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
] as const satisfies ModelDefinition[];