import type { ModelDefinition } from "../models";

export const mistralModels = [
	{
		id: "mistral-large-latest",
		name: "Mistral Large Latest",
		family: "mistral",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "mistral",
				modelName: "mistral-large-latest",
				inputPrice: 0.000004,
				outputPrice: 0.000012,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: false,
	},
	{
		id: "mistral-nemo-instruct-2407",
		name: "Mistral Nemo Instruct 2407",
		family: "mistral",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "nebius",
				modelName: "mistralai/Mistral-Nemo-Instruct-2407",
				inputPrice: 0.04 / 1e6,
				outputPrice: 0.12 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "mixtral-8x7b-instruct-together",
		name: "Mixtral 8x7B Instruct",
		family: "mistral",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "together.ai",
				modelName: "mistralai/mixtral-8x7b-instruct-v0.1",
				inputPrice: 0.06 / 1e6,
				outputPrice: 0.06 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "mistral-7b-instruct-together",
		name: "Mistral 7B Instruct",
		family: "mistral",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "together.ai",
				modelName: "mistralai/mistral-7b-instruct-v0.1",
				inputPrice: 0.06 / 1e6,
				outputPrice: 0.06 / 1e6,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
] as const satisfies ModelDefinition[];