import type { ModelDefinition } from "../models";

export const openaiModels = [
	{
		id: "gpt-4o-mini",
		name: "GPT-4o Mini",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4o-mini",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.075 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-4",
		name: "GPT-4",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4",
				inputPrice: 30.0 / 1e6,
				outputPrice: 60.0 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
		],
		jsonOutput: false,
	},
	{
		id: "gpt-4o",
		name: "GPT-4o",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4o",
				inputPrice: 2.5 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 1.25 / 1e6,
				requestPrice: 0,
				imageInputPrice: 0.00553,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: true,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-3.5-turbo",
		name: "GPT-3.5 Turbo",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-3.5-turbo",
				inputPrice: 0.5 / 1e6,
				outputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 16385,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-4-turbo",
		name: "GPT-4 Turbo",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4-turbo",
				inputPrice: 10.0 / 1e6,
				outputPrice: 30.0 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-4.1",
		name: "GPT-4.1",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4.1",
				inputPrice: 2.0 / 1e6,
				outputPrice: 8.0 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "o1",
		name: "o1",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "o1",
				inputPrice: 15.0 / 1e6,
				outputPrice: 60.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				reasoning: true,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	// TODO this model does not support the system role in the messages array (jeez openai)
	// {
	// 	model: "o1-mini",
	// 	deprecatedAt: undefined,
	// 	deactivatedAt: undefined,
	// 	providers: [
	// 		{
	// 			providerId: "openai",
	// 			modelName: "o1-mini",
	// 			inputPrice: 1.1 / 1e6,
	// 			outputPrice: 4.4 / 1e6, requestPrice: 0,
	// 			contextSize: 128000, maxOutput: undefined,
	// 			streaming: true,
	// 			reasoning: true,
	// 		},
	// 	],
	// 	jsonOutput: true,
	// },
	{
		id: "gpt-4.1-mini",
		name: "GPT-4.1 Mini",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4.1-mini",
				inputPrice: 0.4 / 1e6,
				outputPrice: 1.6 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-4.1-nano",
		name: "GPT-4.1 Nano",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4.1-nano",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "o3",
		name: "o3",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "o3",
				inputPrice: 2 / 1e6,
				outputPrice: 8 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: false,
				vision: true,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "o3-mini",
		name: "o3 Mini",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "o3-mini",
				inputPrice: 1.1 / 1e6,
				outputPrice: 4.4 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-oss-120b",
		name: "GPT OSS 120B",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "groq",
				modelName: "openai/gpt-oss-120b",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.75 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32766,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-oss-20b",
		name: "GPT OSS 20B",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "groq",
				modelName: "openai/gpt-oss-20b",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.5 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32766,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-5",
		name: "GPT-5",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-5-mini",
		name: "GPT-5 Mini",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5-mini",
				inputPrice: 0.25 / 1e6,
				outputPrice: 2 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-5-nano",
		name: "GPT-5 Nano",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5-nano",
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.005 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
		],
		jsonOutput: true,
	},
	{
		id: "gpt-5-chat-latest",
		name: "GPT-5 Chat Latest",
		family: "openai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5-chat-latest",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: false,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
				],
			},
		],
		jsonOutput: true,
	},
] as const satisfies ModelDefinition[];