import type { ModelDefinition } from "../models";

export const xaiModels = [
	{
		id: "grok-3",
		name: "Grok-3",
		family: "xai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "xai",
				modelName: "grok-3",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "grok-3-mini",
		name: "Grok-3 Mini",
		family: "xai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "xai",
				modelName: "grok-3-mini",
				inputPrice: 0.3 / 1e6,
				outputPrice: 0.5 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "grok-3-fast",
		name: "Grok-3 Fast",
		family: "xai",
		deprecatedAt: new Date("2025-08-08"),
		deactivatedAt: new Date("2025-09-15"),
		providers: [
			{
				providerId: "xai",
				modelName: "grok-3-fast",
				inputPrice: 5.0 / 1e6,
				outputPrice: 25.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "grok-3-mini-fast",
		name: "Grok-3 Mini Fast",
		family: "xai",
		deprecatedAt: new Date("2025-08-08"),
		deactivatedAt: new Date("2025-09-15"),
		providers: [
			{
				providerId: "xai",
				modelName: "grok-3-mini-fast",
				inputPrice: 0.6 / 1e6,
				outputPrice: 4.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "grok-2-1212",
		name: "Grok-2 (1212)",
		family: "xai",
		deprecatedAt: new Date("2025-08-08"),
		deactivatedAt: new Date("2025-09-15"),
		providers: [
			{
				providerId: "xai",
				modelName: "grok-2-1212",
				inputPrice: 2.0 / 1e6,
				outputPrice: 10.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "grok-2-vision-1212",
		name: "Grok-2 Vision (1212)",
		family: "xai",
		deprecatedAt: new Date("2025-08-08"),
		deactivatedAt: new Date("2025-09-15"),
		providers: [
			{
				providerId: "xai",
				modelName: "grok-2-vision-1212",
				inputPrice: 2.0 / 1e6,
				outputPrice: 10.0 / 1e6,
				requestPrice: 0,
				imageInputPrice: 2.0 / 1e6,
				contextSize: 32768,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "grok-4-0709",
		name: "Grok-4 (0709)",
		family: "xai",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "xai",
				modelName: "grok-4-0709",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				requestPrice: 0,
				imageInputPrice: undefined,
				contextSize: 256000,
				maxOutput: 256000,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
] as const satisfies ModelDefinition[];