import type { ModelDefinition } from "../models";

export const zaiModels = [
	{
		id: "glm-4.5",
		name: "GLM-4.5",
		family: "glm",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5",
				inputPrice: 0.11 / 1e6,
				outputPrice: 0.28 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "glm-4.5-air",
		name: "GLM-4.5 Air",
		family: "glm",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5-air",
				inputPrice: 0.11 / 1e6,
				outputPrice: 0.28 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "glm-4.5-x",
		name: "GLM-4.5 X",
		family: "glm",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5-x",
				inputPrice: 0.11 / 1e6,
				outputPrice: 0.28 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
			},
		],
		jsonOutput: true,
	},
	{
		id: "glm-4.5-airx",
		name: "GLM-4.5 AirX",
		family: "glm",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5-airx",
				inputPrice: 0.11 / 1e6,
				outputPrice: 0.28 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "glm-4.5-flash",
		name: "GLM-4.5 Flash",
		family: "glm",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5-flash",
				inputPrice: 0.11 / 1e6,
				outputPrice: 0.28 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
	{
		id: "glm-4-32b-0414-128k",
		name: "GLM-4 32B (0414-128k)",
		family: "glm",
		deprecatedAt: undefined,
		deactivatedAt: undefined,
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4-32b-0414-128k",
				inputPrice: 0.11 / 1e6,
				outputPrice: 0.28 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
		jsonOutput: true,
	},
] as const satisfies ModelDefinition[];