# https://just.systems

install:
    uv sync --all-extras

lint:
    uv run ruff format .
    uv run ruff check --fix .
    uv run ty check outpost/ tests/

lint-check:
    uv run ruff format --check .
    uv run ruff check .
    uv run ty check outpost/ tests/

test:
    uv run pytest

dev:
    docker compose up -d
    uv run uvicorn outpost:app --reload --port 9000

default_workers := '1'

up workers=default_workers:
    docker compose up -d
    uv run uvicorn outpost:app --port 9000 --workers {{workers}}
