export interface Model {
  model: string
  providers: string
  contextSize: string
  inputPrice: string
  outputPrice: string
}

export const models: Model[] = [
  {
    model: 'openaigpt-4o-mini',
    providers: 'OpenAI',
    contextSize: '128k',
    inputPrice: '$0.15/M',
    outputPrice: '$0.60/M',
  },
  {
    model: 'openaigpt-4',
    providers: 'OpenAI',
    contextSize: '128k',
    inputPrice: '$30.00/M',
    outputPrice: '$60.00/M',
  },
  {
    model: 'openaigpt-4o',
    providers: 'OpenAI',
    contextSize: '128k',
    inputPrice: '$2.50/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'openaigpt-3.5-turbo',
    providers: 'OpenAI',
    contextSize: '16.4k',
    inputPrice: '$0.50/M',
    outputPrice: '$1.50/M',
  },
  {
    model: 'openaigpt-4-turbo',
    providers: 'OpenAI',
    contextSize: '128k',
    inputPrice: '$10.00/M',
    outputPrice: '$30.00/M',
  },
  {
    model: 'openaigpt-4.1',
    providers: 'OpenAI',
    contextSize: '1M',
    inputPrice: '$2.00/M',
    outputPrice: '$8.00/M',
  },
  {
    model: 'openaio1',
    providers: 'OpenAI',
    contextSize: '200k',
    inputPrice: '$15.00/M',
    outputPrice: '$60.00/M',
  },
  {
    model: 'openaigpt-4.1-mini',
    providers: 'OpenAI',
    contextSize: '1M',
    inputPrice: '$0.40/M',
    outputPrice: '$1.60/M',
  },
  {
    model: 'openaigpt-4.1-nano',
    providers: 'OpenAI',
    contextSize: '1M',
    inputPrice: '$0.10/M',
    outputPrice: '$0.40/M',
  },
  {
    model: 'openaio3',
    providers: 'OpenAI',
    contextSize: '200k',
    inputPrice: '$2.00/M',
    outputPrice: '$8.00/M',
  },
  {
    model: 'openaio3-mini',
    providers: 'OpenAI',
    contextSize: '200k',
    inputPrice: '$1.10/M',
    outputPrice: '$4.40/M',
  },
  {
    model: 'openaigpt-oss-120b',
    providers: 'Groq',
    contextSize: '131.1k',
    inputPrice: '$0.15/M',
    outputPrice: '$0.75/M',
  },
  {
    model: 'openaigpt-oss-20b',
    providers: 'Groq',
    contextSize: '131.1k',
    inputPrice: '$0.10/M',
    outputPrice: '$0.50/M',
  },
  {
    model: 'openaigpt-5',
    providers: 'OpenAI',
    contextSize: '400k',
    inputPrice: '$1.25/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'openaigpt-5-mini',
    providers: 'OpenAI',
    contextSize: '400k',
    inputPrice: '$0.25/M',
    outputPrice: '$2.00/M',
  },
  {
    model: 'openaigpt-5-nano',
    providers: 'OpenAI',
    contextSize: '400k',
    inputPrice: '$0.05/M',
    outputPrice: '$0.40/M',
  },
  {
    model: 'openaigpt-5-chat-latest',
    providers: 'OpenAI',
    contextSize: '400k',
    inputPrice: '$1.25/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'anthropicclaude-3-7-sonnet',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'anthropicclaude-3-7-sonnet-20250219',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'anthropicclaude-3-5-sonnet-20241022',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'anthropicclaude-2.1',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$8.00/M',
    outputPrice: '$24.00/M',
  },
  {
    model: 'anthropicclaude-sonnet-4-20250514',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'anthropicclaude-opus-4-20250514',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$15.00/M',
    outputPrice: '$75.00/M',
  },
  {
    model: 'anthropicclaude-opus-4-1',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$15.00/M',
    outputPrice: '$75.00/M',
  },
  {
    model: 'anthropicclaude-3-5-sonnet',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'googlegemini-2.5-pro',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$1.25/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'googlegemini-2.5-pro-preview-05-06',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$1.25/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'googlegemini-2.5-pro-preview-06-05',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$1.25/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'googlegemini-2.5-flash-preview-04-17',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.15/M',
    outputPrice: '$0.60/M',
  },
  {
    model: 'googlegemini-2.5-flash-preview-05-20',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.15/M',
    outputPrice: '$0.60/M',
  },
  {
    model: 'googlegemini-2.5-flash',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.15/M',
    outputPrice: '$0.60/M',
  },
  {
    model: 'googlegemini-2.5-flash-preview-04-17-thinking',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.15/M',
    outputPrice: '$0.60/M',
  },
  {
    model: 'googlegemini-1.5-pro',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.04/M',
    outputPrice: '$0.15/M',
  },
  {
    model: 'googlegemini-1.5-flash',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.04/M',
    outputPrice: '$0.15/M',
  },
  {
    model: 'googlegemini-1.5-flash-8b',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.04/M',
    outputPrice: '$0.15/M',
  },
  {
    model: 'googlegemini-2.0-flash-lite',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.07/M',
    outputPrice: '$0.30/M',
  },
  {
    model: 'googlegemini-2.0-flash',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.10/M',
    outputPrice: '$0.40/M',
  },
  {
    model: 'googlegemma-3n-e2b-it',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.07/M',
    outputPrice: '$0.30/M',
  },
  {
    model: 'googlegemma-3n-e4b-it',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.07/M',
    outputPrice: '$0.30/M',
  },
  {
    model: 'googlegemma-3-1b-it',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.07/M',
    outputPrice: '$0.30/M',
  },
  {
    model: 'googlegemma-3-4b-it',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.07/M',
    outputPrice: '$0.30/M',
  },
  {
    model: 'googlegemma-3-12b-it',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.07/M',
    outputPrice: '$0.30/M',
  },
  {
    model: 'googlegemma2-9b-it',
    providers: 'Groq',
    contextSize: '8.1k',
    inputPrice: '$0.20/M',
    outputPrice: '$0.20/M',
  },
  {
    model: 'googlegemma-3-27b',
    providers: 'Nebius AI',
    contextSize: '128k',
    inputPrice: '$0.27/M',
    outputPrice: '$0.27/M',
  },
  {
    model: 'googlegemma-2-27b-it-together',
    providers: 'Together AI',
    contextSize: '8.2k',
    inputPrice: '$0.08/M',
    outputPrice: '$0.08/M',
  },
  {
    model: 'perplexitysonar-reasoning-pro',
    providers: 'Perplexity',
    contextSize: '128k',
    inputPrice: '$3.00/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'perplexitysonar-pro',
    providers: 'Perplexity',
    contextSize: '200k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'perplexitysonar',
    providers: 'Perplexity',
    contextSize: '130k',
    inputPrice: '$1.00/M',
    outputPrice: '$1.00/M',
  },
  {
    model: 'xaigrok-3',
    providers: 'xAI',
    contextSize: '131.1k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'xaigrok-3-mini',
    providers: 'xAI',
    contextSize: '131.1k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'openaigpt-4',
    providers: 'OpenAI',
    contextSize: '128k',
    inputPrice: '$30.00/M',
    outputPrice: '$60.00/M',
  },
  {
    model: 'openaigpt-4o',
    providers: 'OpenAI',
    contextSize: '128k',
    inputPrice: '$2.50/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'openaigpt-3.5-turbo',
    providers: 'OpenAI',
    contextSize: '16.4k',
    inputPrice: '$0.50/M',
    outputPrice: '$1.50/M',
  },
  {
    model: 'openaigpt-4-turbo',
    providers: 'OpenAI',
    contextSize: '128k',
    inputPrice: '$10.00/M',
    outputPrice: '$30.00/M',
  },
  {
    model: 'openaigpt-4.1',
    providers: 'OpenAI',
    contextSize: '1M',
    inputPrice: '$2.00/M',
    outputPrice: '$8.00/M',
  },
  {
    model: 'openaio1',
    providers: 'OpenAI',
    contextSize: '200k',
    inputPrice: '$15.00/M',
    outputPrice: '$60.00/M',
  },
  {
    model: 'openaigpt-4.1-mini',
    providers: 'OpenAI',
    contextSize: '1M',
    inputPrice: '$0.40/M',
    outputPrice: '$1.60/M',
  },
  {
    model: 'openaigpt-4.1-nano',
    providers: 'OpenAI',
    contextSize: '1M',
    inputPrice: '$0.10/M',
    outputPrice: '$0.40/M',
  },
  {
    model: 'openaio3',
    providers: 'OpenAI',
    contextSize: '200k',
    inputPrice: '$2.00/M',
    outputPrice: '$8.00/M',
  },
  {
    model: 'openaio3-mini',
    providers: 'OpenAI',
    contextSize: '200k',
    inputPrice: '$1.10/M',
    outputPrice: '$4.40/M',
  },
  {
    model: 'openaigpt-oss-120b',
    providers: 'Groq',
    contextSize: '131.1k',
    inputPrice: '$0.15/M',
    outputPrice: '$0.75/M',
  },
  {
    model: 'openaigpt-oss-20b',
    providers: 'Groq',
    contextSize: '131.1k',
    inputPrice: '$0.10/M',
    outputPrice: '$0.50/M',
  },
  {
    model: 'openaigpt-5',
    providers: 'OpenAI',
    contextSize: '400k',
    inputPrice: '$1.25/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'openaigpt-5-mini',
    providers: 'OpenAI',
    contextSize: '400k',
    inputPrice: '$0.25/M',
    outputPrice: '$2.00/M',
  },
  {
    model: 'openaigpt-5-nano',
    providers: 'OpenAI',
    contextSize: '400k',
    inputPrice: '$0.05/M',
    outputPrice: '$0.40/M',
  },
  {
    model: 'openaigpt-5-chat-latest',
    providers: 'OpenAI',
    contextSize: '400k',
    inputPrice: '$1.25/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'anthropicclaude-3-7-sonnet',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'anthropicclaude-3-7-sonnet-20250219',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'anthropicclaude-3-5-sonnet-20241022',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'anthropicclaude-2.1',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$8.00/M',
    outputPrice: '$24.00/M',
  },
  {
    model: 'anthropicclaude-sonnet-4-20250514',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'anthropicclaude-opus-4-20250514',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$15.00/M',
    outputPrice: '$75.00/M',
  },
  {
    model: 'anthropicclaude-opus-4-1',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$15.00/M',
    outputPrice: '$75.00/M',
  },
  {
    model: 'anthropicclaude-3-5-sonnet',
    providers: 'Anthropic',
    contextSize: '200k',
    inputPrice: '$3.00/M',
    outputPrice: '$15.00/M',
  },
  {
    model: 'googlegemini-2.5-pro',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$1.25/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'googlegemini-2.5-pro-preview-05-06',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$1.25/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'googlegemini-2.5-pro-preview-06-05',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$1.25/M',
    outputPrice: '$10.00/M',
  },
  {
    model: 'googlegemini-2.5-flash-preview-04-17',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.15/M',
    outputPrice: '$0.60/M',
  },
  {
    model: 'googlegemini-2.5-flash-preview-05-20',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.15/M',
    outputPrice: '$0.60/M',
  },
  {
    model: 'googlegemini-2.5-flash',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.15/M',
    outputPrice: '$0.60/M',
  },
  {
    model: 'googlegemini-2.5-flash-preview-04-17-thinking',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.15/M',
    outputPrice: '$0.60/M',
  },
  {
    model: 'googlegemini-1.5-pro',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.04/M',
    outputPrice: '$0.15/M',
  },
  {
    model: 'googlegemini-1.5-flash',
    providers: 'Google AI Studio',
    contextSize: '1M',
    inputPrice: '$0.04/M',
    outputPrice: '$0.15/M',
  },
]
