/* tslint:disable */
/* eslint-disable */
/**
 * Polar API
 *  Welcome to the **Polar API** for [polar.sh](https://polar.sh).  The Public API is currently a [work in progress](https://github.com/polarsource/polar/issues/834) and is in active development. 🚀  #### Authentication  Use a [Personal Access Token](https://polar.sh/settings) and send it in the `Authorization` header on the format `Bearer [YOUR_TOKEN]`.  #### Feedback  If you have any feedback or comments, reach out in the [Polar API-issue](https://github.com/polarsource/polar/issues/834), or reach out on the Polar Discord server.  We\'d love to see what you\'ve built with the API and to get your thoughts on how we can make the API better!  #### Connecting  The Polar API is online at `https://api.polar.sh`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PolarIntegrationsStripeEndpointsWebhookResponse
 */
export interface PolarIntegrationsStripeEndpointsWebhookResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PolarIntegrationsStripeEndpointsWebhookResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof PolarIntegrationsStripeEndpointsWebhookResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof PolarIntegrationsStripeEndpointsWebhookResponse
     */
    job_id?: string;
}

/**
 * Check if a given object implements the PolarIntegrationsStripeEndpointsWebhookResponse interface.
 */
export function instanceOfPolarIntegrationsStripeEndpointsWebhookResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;

    return isInstance;
}

export function PolarIntegrationsStripeEndpointsWebhookResponseFromJSON(json: any): PolarIntegrationsStripeEndpointsWebhookResponse {
    return PolarIntegrationsStripeEndpointsWebhookResponseFromJSONTyped(json, false);
}

export function PolarIntegrationsStripeEndpointsWebhookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolarIntegrationsStripeEndpointsWebhookResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'job_id': !exists(json, 'job_id') ? undefined : json['job_id'],
    };
}

export function PolarIntegrationsStripeEndpointsWebhookResponseToJSON(value?: PolarIntegrationsStripeEndpointsWebhookResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'job_id': value.job_id,
    };
}

