AUTHORIZATION_CODE_PREFIX = "polar_ac_"
ACCESS_TOKEN_PREFIX = "polar_at_"
REFRESH_TOKEN_PREFIX = "polar_rt_"

SCOPES_SUPPORTED = ["openid", "profile", "email"]


__all__ = [
    "AUTHORIZATION_CODE_PREFIX",
    "ACCESS_TOKEN_PREFIX",
    "REFRESH_TOKEN_PREFIX",
    "SCOPES_SUPPORTED",
]
