/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { PolarCore } from "../core.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { Wallet, Wallet$inboundSchema } from "../models/components/wallet.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import {
  HTTPValidationError,
  HTTPValidationError$inboundSchema,
} from "../models/errors/httpvalidationerror.js";
import {
  MissingPaymentMethodError,
  MissingPaymentMethodError$inboundSchema,
} from "../models/errors/missingpaymentmethoderror.js";
import {
  PaymentIntentFailedError,
  PaymentIntentFailedError$inboundSchema,
} from "../models/errors/paymentintentfailederror.js";
import { PolarError } from "../models/errors/polarerror.js";
import {
  ResourceNotFound,
  ResourceNotFound$inboundSchema,
} from "../models/errors/resourcenotfound.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  WalletsTopUpRequest,
  WalletsTopUpRequest$outboundSchema,
} from "../models/operations/walletstopup.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Top-Up Wallet
 *
 * @remarks
 * Top-up a wallet by adding funds to its balance.
 *
 * The customer should have a valid payment method on file.
 *
 * **Scopes**: `wallets:write`
 */
export function walletsTopUp(
  client: PolarCore,
  request: WalletsTopUpRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    Wallet | undefined,
    | PaymentIntentFailedError
    | MissingPaymentMethodError
    | ResourceNotFound
    | HTTPValidationError
    | PolarError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: PolarCore,
  request: WalletsTopUpRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      Wallet | undefined,
      | PaymentIntentFailedError
      | MissingPaymentMethodError
      | ResourceNotFound
      | HTTPValidationError
      | PolarError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => z.parse(WalletsTopUpRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload.WalletTopUpCreate, { explode: true });

  const pathParams = {
    id: encodeSimple("id", payload.id, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc("/v1/wallets/{id}/top-up")(pathParams);

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.accessToken);
  const securityInput = secConfig == null ? {} : { accessToken: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "wallets:top_up",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.accessToken,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["400", "402", "404", "422", "4XX", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    Wallet | undefined,
    | PaymentIntentFailedError
    | MissingPaymentMethodError
    | ResourceNotFound
    | HTTPValidationError
    | PolarError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, z.optional(Wallet$inboundSchema)),
    M.nil(201, z.optional(Wallet$inboundSchema)),
    M.jsonErr(400, PaymentIntentFailedError$inboundSchema),
    M.jsonErr(402, MissingPaymentMethodError$inboundSchema),
    M.jsonErr(404, ResourceNotFound$inboundSchema),
    M.jsonErr(422, HTTPValidationError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
