// Generated from discounts:update (2026-04). Do not edit.
import type { Polar } from '@polar-sh/sdk/2026-04'
import { Effect } from 'effect'
import { Argument, Command, Flag } from 'effect/unstable/cli'
import { ApiRuntime } from '../runtime'
import { data, mergeInput, jsonFlag } from '../inputs'

type Body = NonNullable<Parameters<Polar['discounts']['update']>[1]>

export const command = Command.make(
  'update',
  {
    path: {
      id: Argument.string('id'),
    },
    data,
    input: {
      metadata: jsonFlag('metadata').pipe(
        Flag.optional,
        Flag.withDescription(
          'Key-value object allowing you to store additional information.',
        ),
      ),
      name: Flag.string('name').pipe(
        Flag.optional,
        Flag.withDescription('name'),
      ),
      code: Flag.string('code').pipe(
        Flag.optional,
        Flag.withDescription(
          'Code customers can use to apply the discount during checkout. Must be between 3 and 256 characters long and contain only alphanumeric characters.If not provided, the discount can only be applied via the API.',
        ),
      ),
      starts_at: Flag.string('starts-at').pipe(
        Flag.optional,
        Flag.withDescription(
          'Optional timestamp after which the discount is redeemable.',
        ),
      ),
      ends_at: Flag.string('ends-at').pipe(
        Flag.optional,
        Flag.withDescription(
          'Optional timestamp after which the discount is no longer redeemable.',
        ),
      ),
      max_redemptions: Flag.integer('max-redemptions').pipe(
        Flag.optional,
        Flag.withDescription(
          'Optional maximum number of times the discount can be redeemed.',
        ),
      ),
      max_redemptions_per_customer: Flag.integer(
        'max-redemptions-per-customer',
      ).pipe(
        Flag.optional,
        Flag.withDescription(
          'Optional maximum number of times the discount can be redeemed by a single customer.',
        ),
      ),
      duration: Flag.choice('duration', ['once', 'forever', 'repeating']).pipe(
        Flag.optional,
        Flag.withDescription('duration'),
      ),
      duration_in_months: Flag.integer('duration-in-months').pipe(
        Flag.optional,
        Flag.withDescription('duration_in_months'),
      ),
      type: Flag.choice('type', ['fixed', 'percentage']).pipe(
        Flag.optional,
        Flag.withDescription('type'),
      ),
      amount: Flag.integer('amount').pipe(
        Flag.optional,
        Flag.withDescription('amount'),
      ),
      currency: Flag.choice('currency', [
        'aed',
        'all',
        'amd',
        'aoa',
        'ars',
        'aud',
        'awg',
        'azn',
        'bam',
        'bbd',
        'bdt',
        'bif',
        'bmd',
        'bnd',
        'bob',
        'brl',
        'bsd',
        'bwp',
        'bzd',
        'cad',
        'cdf',
        'chf',
        'clp',
        'cny',
        'cop',
        'crc',
        'cve',
        'czk',
        'djf',
        'dkk',
        'dop',
        'dzd',
        'egp',
        'etb',
        'eur',
        'fjd',
        'fkp',
        'gbp',
        'gel',
        'gip',
        'gmd',
        'gnf',
        'gtq',
        'gyd',
        'hkd',
        'hnl',
        'htg',
        'huf',
        'idr',
        'ils',
        'inr',
        'isk',
        'jmd',
        'jpy',
        'kes',
        'kgs',
        'khr',
        'kmf',
        'krw',
        'kyd',
        'kzt',
        'lak',
        'lkr',
        'lrd',
        'lsl',
        'mad',
        'mdl',
        'mga',
        'mkd',
        'mnt',
        'mop',
        'mur',
        'mvr',
        'mwk',
        'mxn',
        'myr',
        'mzn',
        'nad',
        'ngn',
        'nio',
        'nok',
        'npr',
        'nzd',
        'pab',
        'pen',
        'pgk',
        'php',
        'pkr',
        'pln',
        'pyg',
        'qar',
        'ron',
        'rsd',
        'rwf',
        'sar',
        'sbd',
        'scr',
        'sek',
        'sgd',
        'shp',
        'sos',
        'srd',
        'szl',
        'thb',
        'tjs',
        'top',
        'try',
        'ttd',
        'twd',
        'tzs',
        'uah',
        'ugx',
        'usd',
        'uyu',
        'uzs',
        'vnd',
        'vuv',
        'wst',
        'xaf',
        'xcd',
        'xcg',
        'xof',
        'xpf',
        'yer',
        'zar',
        'zmw',
      ]).pipe(Flag.optional, Flag.withDescription('currency')),
      amounts: jsonFlag('amounts').pipe(
        Flag.optional,
        Flag.withDescription('amounts'),
      ),
      basis_points: Flag.integer('basis-points').pipe(
        Flag.optional,
        Flag.withDescription('basis_points'),
      ),
      products: Flag.string('products')
        .pipe(Flag.atLeast(1))
        .pipe(Flag.optional, Flag.withDescription('products')),
    },
  },
  (config) =>
    Effect.gen(function* () {
      const api = yield* ApiRuntime
      const body = mergeInput<Body>(config.data, {
        metadata: config.input.metadata,
        name: config.input.name,
        code: config.input.code,
        starts_at: config.input.starts_at,
        ends_at: config.input.ends_at,
        max_redemptions: config.input.max_redemptions,
        max_redemptions_per_customer: config.input.max_redemptions_per_customer,
        duration: config.input.duration,
        duration_in_months: config.input.duration_in_months,
        type: config.input.type,
        amount: config.input.amount,
        currency: config.input.currency,
        amounts: config.input.amounts,
        basis_points: config.input.basis_points,
        products: config.input.products,
      })
      yield* api.execute({
        operationId: 'discounts:update',
        method: 'PATCH',
        requiresConfirmation: false,
        confirm: false,
        invoke: (client) => client.discounts.update(config.path.id, body),
      })
    }),
).pipe(Command.withDescription('Update a discount.'))
