"""repository.repository_issues_references_synced_at

Revision ID: 7f3d2182a4fb
Revises: 79c64025f7cf
Create Date: 2023-03-21 15:45:06.097254

"""
import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "7f3d2182a4fb"
down_revision = "79c64025f7cf"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repositories",
        sa.Column(
            "repository_issues_references_synced_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "repository_issues_references_synced_at")
    # ### end Alembic commands ###
