"""magic_link.source

Revision ID: a2e9937406e0
Revises: 263c2d960ed4
Create Date: 2023-12-11 10:30:02.469535

"""
import sqlalchemy as sa
from alembic import op

# Polar Custom Imports
from polar.kit.extensions.sqlalchemy import PostgresUUID

# revision identifiers, used by Alembic.
revision = "a2e9937406e0"
down_revision = "263c2d960ed4"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("magic_links", sa.Column("source", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("magic_links", "source")
    # ### end Alembic commands ###
