"""payment_methods

Revision ID: 81d21642cefb
Revises: 983a13692050
Create Date: 2023-09-08 09:34:40.453352

"""
import sqlalchemy as sa
from alembic import op

# Polar Custom Imports
from polar.kit.extensions.sqlalchemy import PostgresUUID

# revision identifiers, used by Alembic.
revision = "81d21642cefb"
down_revision = "983a13692050"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("stripe_customer_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "stripe_customer_id")
    # ### end Alembic commands ###
