"""customize minimum pledge amount

Revision ID: e1649ad1d26b
Revises: c72cb47114df
Create Date: 2023-06-29 12:15:04.936702

"""
import sqlalchemy as sa
from alembic import op

# Polar Custom Imports
from polar.kit.extensions.sqlalchemy import PostgresUUID

# revision identifiers, used by Alembic.
revision = "e1649ad1d26b"
down_revision = "c12e0331363b"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "pledge_minimum_amount",
            sa.Integer(),
            nullable=False,
            server_default="2000",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "pledge_minimum_amount")
    # ### end Alembic commands ###
