"""issue.positive_reactions_count

Revision ID: 06af777f16c6
Revises: 98a7aacb7809
Create Date: 2023-06-07 16:12:54.535552

"""
import sqlalchemy as sa
from alembic import op

# Polar Custom Imports
from polar.kit.extensions.sqlalchemy import PostgresUUID

# revision identifiers, used by Alembic.
revision = "06af777f16c6"
down_revision = "98a7aacb7809"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    op.add_column(
        "issues", sa.Column("positive_reactions_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "issues", sa.Column("total_engagement_count", sa.Integer(), nullable=True)
    )
    op.create_index(
        "idx_issues_positive_reactions_count",
        "issues",
        ["positive_reactions_count"],
        unique=False,
    )
    op.create_index(
        "idx_issues_positive_total_engagement_count",
        "issues",
        ["total_engagement_count"],
        unique=False,
    )

    op.execute(
        """
        UPDATE issues
        SET positive_reactions_count = A.positive_reactions_count,
        total_engagement_count = A.total_engagement_count
        FROM (
            SELECT id, 
            (reactions::json->>'plus_one')::int +
            (reactions::json->>'laugh')::int +
            (reactions::json->>'heart')::int +
            (reactions::json->>'hooray')::int +
            (reactions::json->>'eyes')::int +
            (reactions::json->>'rocket')::int as positive_reactions_count,
            (reactions::json->>'total_count')::int + comments as total_engagement_count
            FROM issues
        ) AS A
        WHERE issues.id = A.id;
    """
    )

    op.alter_column("issues", "positive_reactions_count", nullable=False)
    op.alter_column("issues", "total_engagement_count", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_issues_positive_total_engagement_count", table_name="issues")
    op.drop_index("idx_issues_positive_reactions_count", table_name="issues")
    op.drop_column("issues", "total_engagement_count")
    op.drop_column("issues", "positive_reactions_count")
    # ### end Alembic commands ###
