"""oauth.username

Revision ID: 57d1a318f8e5
Revises: bedd8fdf9f8c
Create Date: 2024-02-05 11:14:59.053973

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports
from polar.kit.extensions.sqlalchemy import PostgresUUID

# revision identifiers, used by Alembic.
revision = "57d1a318f8e5"
down_revision = "bedd8fdf9f8c"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth_accounts",
        sa.Column("account_username", sa.String(length=320), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth_accounts", "account_username")
    # ### end Alembic commands ###
