"""Add DiscountRedemption

Revision ID: 15cf96674f9b
Revises: d4d21e6b4535
Create Date: 2024-11-14 13:16:24.345890

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "15cf96674f9b"
down_revision = "d4d21e6b4535"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discount_redemptions",
        sa.Column("discount_id", sa.Uuid(), nullable=False),
        sa.Column("checkout_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["checkout_id"],
            ["checkouts.id"],
            name=op.f("discount_redemptions_checkout_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["discount_id"],
            ["discounts.id"],
            name=op.f("discount_redemptions_discount_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("discount_redemptions_pkey")),
    )
    op.create_index(
        op.f("ix_discount_redemptions_created_at"),
        "discount_redemptions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discount_redemptions_deleted_at"),
        "discount_redemptions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discount_redemptions_modified_at"),
        "discount_redemptions",
        ["modified_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_discount_redemptions_modified_at"), table_name="discount_redemptions"
    )
    op.drop_index(
        op.f("ix_discount_redemptions_deleted_at"), table_name="discount_redemptions"
    )
    op.drop_index(
        op.f("ix_discount_redemptions_created_at"), table_name="discount_redemptions"
    )
    op.drop_table("discount_redemptions")
    # ### end Alembic commands ###
