"""webhooks_endpoints.organization

Revision ID: c4ebdc0f0482
Revises: 65aaa49b6c56
Create Date: 2024-04-19 13:15:20.510884

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports
from polar.kit.extensions.sqlalchemy import PostgresUUID

# revision identifiers, used by Alembic.
revision = "c4ebdc0f0482"
down_revision = "65aaa49b6c56"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "webhook_endpoints",
        sa.Column(
            "event_organization_updated",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webhook_endpoints", "event_organization_updated")
    # ### end Alembic commands ###
