"""Add Discount.allow_discount_codes

Revision ID: ed6fcf5032cc
Revises: 15cf96674f9b
Create Date: 2024-11-14 15:30:07.915623

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "ed6fcf5032cc"
down_revision = "15cf96674f9b"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checkouts", sa.Column("allow_discount_codes", sa.Boolean(), nullable=True)
    )
    op.execute(
        "UPDATE checkouts SET allow_discount_codes = TRUE WHERE allow_discount_codes IS NULL"
    )
    op.alter_column("checkouts", "allow_discount_codes", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("checkouts", "allow_discount_codes")
    # ### end Alembic commands ###
