"""Use RecordModel for WebhookDelivery and WebhookEvent

Revision ID: abf9bb686a33
Revises: 8b001284e336
Create Date: 2024-04-30 14:36:53.625683

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports
from polar.kit.extensions.sqlalchemy import PostgresUUID

# revision identifiers, used by Alembic.
revision = "abf9bb686a33"
down_revision = "8b001284e336"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "webhook_deliveries",
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "webhook_deliveries",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "webhook_events",
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "webhook_events",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webhook_events", "deleted_at")
    op.drop_column("webhook_events", "modified_at")
    op.drop_column("webhook_deliveries", "deleted_at")
    op.drop_column("webhook_deliveries", "modified_at")
    # ### end Alembic commands ###
