"""add slug to benefits

Revision ID: e3e7299eac73
Revises: c996df1d397f
Create Date: 2025-01-22 14:29:18.854264

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "e3e7299eac73"
down_revision = "c996df1d397f"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("benefits", sa.Column("slug", sa.String(), nullable=True))

    # create slug for existing benefits using a slugify function
    connection = op.get_bind()
    benefits = connection.execute(
        sa.text("SELECT id, description FROM benefits WHERE slug IS NULL")
    ).fetchall()

    for benefit in benefits:
        base_slug = connection.execute(
            sa.text(
                "SELECT regexp_replace(lower(regexp_replace(:description, '[^a-zA-Z0-9]+', '-', 'g')), '-$', '', 'g')"
            ).bindparams(description=benefit.description)
        ).scalar()

        slug = base_slug
        iterator = 0
        while True:
            existing = connection.execute(
                sa.text("SELECT 1 FROM benefits WHERE slug = :slug").bindparams(
                    slug=slug
                )
            ).fetchone()
            if not existing:
                break
            iterator += 1
            slug = f"{base_slug}-{iterator}"

        connection.execute(
            sa.text("UPDATE benefits SET slug = :slug WHERE id = :id").bindparams(
                slug=slug, id=benefit.id
            )
        )

    # Make slug not nullable
    op.alter_column("benefits", "slug", nullable=False)

    op.create_index(
        "ix_benefits_organization_id_slug",
        "benefits",
        ["organization_id", "slug"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_benefits_organization_id_slug", table_name="benefits")
    op.drop_column("benefits", "slug")
    # ### end Alembic commands ###
