"""add violated_aup_section to organization_review_feedback

Revision ID: 94bf1c4552b6
Revises: b181f0be8208
Create Date: 2026-07-03 10:30:00.000000

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "94bf1c4552b6"
down_revision = "b181f0be8208"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_review_feedback",
        sa.Column("violated_aup_section", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_review_feedback", "violated_aup_section")
    # ### end Alembic commands ###
