"""make redemptions_count non-nullable

Revision ID: 6145195fc43a
Revises: 5c9d0e1f2a3b
Create Date: 2026-01-19 21:08:28.113164

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "6145195fc43a"
down_revision = "5c9d0e1f2a3b"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "discounts", "redemptions_count", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "discounts", "redemptions_count", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
