"""add is_auto_reply to support_case_messages

Revision ID: 74ee4dd0496c
Revises: e59a12239bc2
Create Date: 2026-06-23 12:24:38.777585

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "74ee4dd0496c"
down_revision = "e59a12239bc2"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "support_case_messages",
        sa.Column(
            "is_auto_reply", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("support_case_messages", "is_auto_reply")
    # ### end Alembic commands ###
