"""drop member_sessions.token

Revision ID: b2a2d9433961
Revises: f610cb0cda21
Create Date: 2026-09-17 18:26:46.990994

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "b2a2d9433961"
down_revision = "f610cb0cda21"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration.
    # CREATE INDEX CONCURRENTLY needs its own, far larger timeout -- see ADR-0006.
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("member_sessions_token_key"), "member_sessions", type_="unique"
    )
    op.drop_column("member_sessions", "token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration.
    # CREATE INDEX CONCURRENTLY needs its own, far larger timeout -- see ADR-0006.
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_sessions",
        sa.Column("token", sa.CHAR(length=64), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint(
        op.f("member_sessions_token_key"),
        "member_sessions",
        ["token"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
