"""add customer_sessions.token_v2

Revision ID: df20d8b1555c
Revises: 94d3eb98cbab
Create Date: 2026-09-17 16:59:00.246938

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "df20d8b1555c"
down_revision = "94d3eb98cbab"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration.
    # CREATE INDEX CONCURRENTLY needs its own, far larger timeout -- see ADR-0006.
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer_sessions", sa.Column("token_v2", sa.String(length=80), nullable=True)
    )
    op.create_unique_constraint(
        op.f("customer_sessions_token_v2_key"), "customer_sessions", ["token_v2"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration.
    # CREATE INDEX CONCURRENTLY needs its own, far larger timeout -- see ADR-0006.
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("customer_sessions_token_v2_key"), "customer_sessions", type_="unique"
    )
    op.drop_column("customer_sessions", "token_v2")
    # ### end Alembic commands ###
