"""add meter interval to product and subscription

Revision ID: c3f9de841eed
Revises: 2ccabcca866d
Create Date: 2026-06-17 10:34:13.874072

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "c3f9de841eed"
down_revision = "2ccabcca866d"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "meter_interval",
            sa.String(),
            nullable=True,
        ),
    )
    op.add_column(
        "products", sa.Column("meter_interval_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "subscriptions",
        sa.Column(
            "meter_interval",
            sa.String(),
            nullable=True,
        ),
    )
    op.add_column(
        "subscriptions", sa.Column("meter_interval_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "subscriptions",
        sa.Column(
            "current_meter_period_start", sa.TIMESTAMP(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "subscriptions",
        sa.Column(
            "current_meter_period_end", sa.TIMESTAMP(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "current_meter_period_end")
    op.drop_column("subscriptions", "current_meter_period_start")
    op.drop_column("subscriptions", "meter_interval_count")
    op.drop_column("subscriptions", "meter_interval")
    op.drop_column("products", "meter_interval_count")
    op.drop_column("products", "meter_interval")
    # ### end Alembic commands ###
