"""Add customer email verification

Revision ID: 18e67fb1e9fc
Revises: c7f2e9d1a3b6
Create Date: 2026-03-30 11:48:52.339965

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "18e67fb1e9fc"
down_revision = "32c17499cb60"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_email_verifications",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("customer_email_verifications_customer_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("customer_email_verifications_organization_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("customer_email_verifications_pkey")),
    )
    op.create_index(
        op.f("ix_customer_email_verifications_created_at"),
        "customer_email_verifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_email_verifications_customer_id"),
        "customer_email_verifications",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_email_verifications_deleted_at"),
        "customer_email_verifications",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_email_verifications_token_hash"),
        "customer_email_verifications",
        ["token_hash"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_customer_email_verifications_token_hash"),
        table_name="customer_email_verifications",
    )
    op.drop_index(
        op.f("ix_customer_email_verifications_deleted_at"),
        table_name="customer_email_verifications",
    )
    op.drop_index(
        op.f("ix_customer_email_verifications_customer_id"),
        table_name="customer_email_verifications",
    )
    op.drop_index(
        op.f("ix_customer_email_verifications_created_at"),
        table_name="customer_email_verifications",
    )
    op.drop_table("customer_email_verifications")
    # ### end Alembic commands ###
