"""add organization_access_tokens.token_v2

Revision ID: b3adeed6aa55
Revises: ac945e3bc7e8
Create Date: 2026-09-17 16:59:13.801171

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "b3adeed6aa55"
down_revision = "ac945e3bc7e8"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration.
    # CREATE INDEX CONCURRENTLY needs its own, far larger timeout -- see ADR-0006.
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_access_tokens",
        sa.Column("token_v2", sa.String(length=80), nullable=True),
    )
    op.create_unique_constraint(
        op.f("organization_access_tokens_token_v2_key"),
        "organization_access_tokens",
        ["token_v2"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Ensures we don't break app by applying a deadlock-inducing migration.
    # CREATE INDEX CONCURRENTLY needs its own, far larger timeout -- see ADR-0006.
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("organization_access_tokens_token_v2_key"),
        "organization_access_tokens",
        type_="unique",
    )
    op.drop_column("organization_access_tokens", "token_v2")
    # ### end Alembic commands ###
