"""Add back Payout.status with trigger

Revision ID: f87fb3683171
Revises: 11baed68732d
Create Date: 2026-02-19 15:01:06.552711

"""

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "f87fb3683171"
down_revision = "11baed68732d"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_payout_status_update = PGFunction(
        schema="public",
        signature="payout_status_update()",
        definition="RETURNS trigger AS $$\n    DECLARE\n        has_succeeded BOOLEAN;\n        has_attempts BOOLEAN;\n        all_failed BOOLEAN;\n        latest_status TEXT;\n        new_status TEXT;\n        current_status TEXT;\n    BEGIN\n        -- Don't update canceled payouts\n        SELECT status INTO current_status\n        FROM payouts\n        WHERE id = NEW.payout_id;\n\n        IF current_status = 'canceled' THEN\n            RETURN NEW;\n        END IF;\n\n        -- Check if any attempt succeeded\n        SELECT EXISTS(\n            SELECT 1 FROM payout_attempts\n            WHERE payout_id = NEW.payout_id\n            AND status = 'succeeded'\n        ) INTO has_succeeded;\n\n        -- Check if there are any attempts\n        SELECT EXISTS(\n            SELECT 1 FROM payout_attempts\n            WHERE payout_id = NEW.payout_id\n        ) INTO has_attempts;\n\n        -- Get the latest attempt's status\n        SELECT status INTO latest_status\n        FROM payout_attempts\n        WHERE payout_id = NEW.payout_id\n        ORDER BY created_at DESC\n        LIMIT 1;\n\n        -- Check if all attempts failed\n        SELECT has_attempts AND NOT EXISTS(\n            SELECT 1 FROM payout_attempts\n            WHERE payout_id = NEW.payout_id\n            AND status != 'failed'\n        ) INTO all_failed;\n\n        -- Determine new status\n        IF has_succeeded THEN\n            new_status := 'succeeded';\n        ELSIF NOT has_attempts THEN\n            new_status := 'pending';\n        ELSIF latest_status = 'in_transit' THEN\n            new_status := 'in_transit';\n        ELSIF all_failed THEN\n            new_status := 'failed';\n        ELSE\n            new_status := 'pending';\n        END IF;\n\n        -- Update the payout status\n        UPDATE payouts\n        SET status = new_status\n        WHERE id = NEW.payout_id;\n\n        RETURN NEW;\n    END\n    $$ LANGUAGE plpgsql",
    )
    op.create_entity(public_payout_status_update)

    public_payout_attempts_payout_status_update_trigger = PGTrigger(
        schema="public",
        signature="payout_status_update_trigger",
        on_entity="public.payout_attempts",
        is_constraint=False,
        definition="AFTER INSERT OR UPDATE ON payout_attempts\n    FOR EACH ROW EXECUTE FUNCTION payout_status_update()",
    )
    op.create_entity(public_payout_attempts_payout_status_update_trigger)

    op.add_column(
        "payouts",
        sa.Column("status", sa.String(), nullable=True),
    )

    op.execute(
        """
        UPDATE payout_attempts SET id = id
        """
    )
    op.alter_column("payouts", "status", nullable=False)

    op.create_index(op.f("ix_payouts_status"), "payouts", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payouts_status"), table_name="payouts")
    op.drop_column("payouts", "status")
    public_payout_attempts_payout_status_update_trigger = PGTrigger(
        schema="public",
        signature="payout_status_update_trigger",
        on_entity="public.payout_attempts",
        is_constraint=False,
        definition="AFTER INSERT OR UPDATE ON payout_attempts\n    FOR EACH ROW EXECUTE FUNCTION payout_status_update()",
    )
    op.drop_entity(public_payout_attempts_payout_status_update_trigger)

    public_payout_status_update = PGFunction(
        schema="public",
        signature="payout_status_update()",
        definition="RETURNS trigger AS $$\n    DECLARE\n        has_succeeded BOOLEAN;\n        has_attempts BOOLEAN;\n        all_failed BOOLEAN;\n        latest_status TEXT;\n        new_status TEXT;\n        current_status TEXT;\n    BEGIN\n        -- Don't update canceled payouts\n        SELECT status INTO current_status\n        FROM payouts\n        WHERE id = NEW.payout_id;\n\n        IF current_status = 'canceled' THEN\n            RETURN NEW;\n        END IF;\n\n        -- Check if any attempt succeeded\n        SELECT EXISTS(\n            SELECT 1 FROM payout_attempts\n            WHERE payout_id = NEW.payout_id\n            AND status = 'succeeded'\n        ) INTO has_succeeded;\n\n        -- Check if there are any attempts\n        SELECT EXISTS(\n            SELECT 1 FROM payout_attempts\n            WHERE payout_id = NEW.payout_id\n        ) INTO has_attempts;\n\n        -- Get the latest attempt's status\n        SELECT status INTO latest_status\n        FROM payout_attempts\n        WHERE payout_id = NEW.payout_id\n        ORDER BY created_at DESC\n        LIMIT 1;\n\n        -- Check if all attempts failed\n        SELECT has_attempts AND NOT EXISTS(\n            SELECT 1 FROM payout_attempts\n            WHERE payout_id = NEW.payout_id\n            AND status != 'failed'\n        ) INTO all_failed;\n\n        -- Determine new status\n        IF has_succeeded THEN\n            new_status := 'succeeded';\n        ELSIF NOT has_attempts THEN\n            new_status := 'pending';\n        ELSIF latest_status = 'in_transit' THEN\n            new_status := 'in_transit';\n        ELSIF all_failed THEN\n            new_status := 'failed';\n        ELSE\n            new_status := 'pending';\n        END IF;\n\n        -- Update the payout status\n        UPDATE payouts\n        SET status = new_status\n        WHERE id = NEW.payout_id;\n\n        RETURN NEW;\n    END\n    $$ LANGUAGE plpgsql",
    )
    op.drop_entity(public_payout_status_update)

    # ### end Alembic commands ###
