"""Make price_currency non nullable

Revision ID: 91e2e5df6a7f
Revises: 64f3c8195104
Create Date: 2026-02-03 14:16:39.439108

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "91e2e5df6a7f"
down_revision = "64f3c8195104"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE product_prices SET price_currency = 'usd' WHERE price_currency IS NULL"
    )

    op.alter_column(
        "product_prices",
        "price_currency",
        existing_type=sa.VARCHAR(length=3),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product_prices",
        "price_currency",
        existing_type=sa.VARCHAR(length=3),
        nullable=True,
    )
    # ### end Alembic commands ###
