# https://just.systems

install:
    uv sync --all-extras

lint:
    uv run ruff format .
    uv run ruff check --fix .
    uv run ty check .

lint-check:
    uv run ruff format --check .
    uv run ruff check .
    uv run ty check .
