site_name: Polar
repo_url: https://github.com/polarsource/polar
repo_name: polarsource/polar
plugins:
  - search
  - macros:
      include_dir: include
theme:
  name: material
  custom_dir: overrides
  logo_light: assets/polar-logo-blue.svg
  logo_dark: assets/polar-logo-white.svg
  favicon: assets/favicon.png
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sticky
    - navigation.expand
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: polar-light
      primary: indigo
      accent: indigo
      toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: polar-dark
      primary: indigo
      accent: indigo
      toggle:
          icon: material/weather-night
          name: Switch to light mode

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@polar_sh
      name: polar_sh on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/polarsource
      name: polarsource on GitHub

extra_css:
  - stylesheets/extra.css


nav:
  - Home:
    - index.md
  - For Maintainers:
    - Issue Funding:
      - Overview: maintainers/issue-funding/index.md
      - Getting Started:
        - 1. Account Setup: maintainers/issue-funding/getting-started/setup-account.md
        - 2. Install GitHub App: maintainers/issue-funding/getting-started/app-installation.md
        - 3. Customize Polar Badge: maintainers/issue-funding/getting-started/badge-settings.md
      - Workflow: maintainers/issue-funding/workflow.md
      - Promote Funding: maintainers/issue-funding/promote.md
    - FAQ: maintainers/faq.md
  - API:
    - Documentation (Alpha): api/index.md
    - GitHub Actions: api/github-action.md
  - FAQ:
    - Overview: faq/index.md
    - For Maintainers: faq/maintainers.md
    - For Backers: faq/backers.md
    - For Contributors: faq/contributors.md
  - Support: support.md
