export const investors = [
  { name: 'Accel', company: 'Venture Capital Firm' },
  { name: 'Abstract', company: 'Venture Capital Firm' },
  { name: 'Mischief', company: 'Venture Capital Firm' },
  { name: 'Guillermo Rauch', company: 'Vercel' },
  { name: 'Paul Copplestone', company: 'Supabase' },
  { name: 'Tobi Lütke', company: 'Shopify' },
  { name: 'Anton Osika', company: 'Lovable' },
  { name: 'Michael Grinich', company: 'WorkOS' },
  { name: 'Thomas Paul Mann', company: 'Raycast' },
  { name: 'Jorn van Dijk & Koen Bok', company: 'Framer' },
  { name: 'Harley Finkelstein', company: 'Shopify' },
  { name: 'Jared Palmer', company: 'GitHub & Microsoft' },
  { name: 'Zeno Rocha', company: 'Resend' },
  { name: 'Steven Tey', company: 'Dub' },
  { name: 'Sébastien & Alexandre Chopin', company: 'Nuxt' },
  { name: 'Gustaf Alstromer', company: 'Y Combinator' },
  { name: 'Mitchell Hashimoto', company: 'Ghostty' },
  { name: 'David Cramer', company: 'Sentry' },
  { name: 'Carl Rivera', company: 'Shopify' },
  { name: 'Kaj Drobin', company: 'Stilla' },
  { name: 'Siavash Ghorbani', company: 'Stilla' },
  { name: 'Fredrik Björk', company: 'Grafbase' },
  { name: 'Joel Hellermark', company: 'Sana' },
  { name: 'Andrea Wang', company: 'SV Angel' },
  { name: 'Kieran Flanagan', company: 'HubSpot' },
  { name: 'Sri Batchu', company: 'The RealReal' },
  { name: 'Tristan Handy', company: 'dbt Labs' },
  { name: 'Mattias Miksche', company: '—' },
]
